bluez5: ignore incompatible-pointer-types, implicit-function-declaration issues
These are fatal by default with gcc-14.

This should be properly fixed by component owner, this is just temporary
work around.

bluez-5.72/src/main.c:1042:41: error: passing argument 4 of 'parse_config_bool' from incompatible pointer type [-Wincompatible-pointer-types]
caused by 0012-Support-enabling-avdtp-delayReport.patch

bluez-5.72/profiles/audio/avrcp.c:4004:9: error: implicit declaration of function 'set_avrcp_ct_supported_events' [-Wimplicit-function-declaration]
caused by 0017-AVRCP-getting-supported-notification-events.patch

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>