novacomd: use gnu17 even with gcc-15
gcc-15 uses gnu23 standard for c since:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212
but this component isn't readly for it and fails to build.

novacomd/2.0.0-124+git/git/include/platform.h:56:13: error: 'bool' cannot be defined via 'typedef'

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>