leveldb, libdrm: move bbappens from meta-luneui to meta-luneos
* helps a bit with yocto-check-layer signature test

INFO: ======================================================================
INFO: FAIL: test_signatures (common.CommonCheckLayer.test_signatures)
INFO: ----------------------------------------------------------------------
INFO: Traceback (most recent call last):
  File "/OE/build/oe-core/openembedded-core/scripts/lib/checklayer/cases/common.py", line 99, in test_signatures
    self.fail('Adding layer %s changed signatures.\n%s' % (self.tc.layer['name'], msg))
AssertionError: Adding layer meta-luneui changed signatures.
318 signatures changed, initial differences (first hash before, second after):
   leveldb:do_collect_spdx_deps: 0efb6273c638f08f2f7aa2255b567d6173787cbfcab3f89b97bfb6e335bb71f8 -> eb325d39e7af5beffe35db7b9d98918ebc58b328cbb9e75f2d7686a992e554e4
      bitbake-diffsigs --task leveldb do_collect_spdx_deps --signature 0efb6273c638f08f2f7aa2255b567d6173787cbfcab3f89b97bfb6e335bb71f8 eb325d39e7af5beffe35db7b9d98918ebc58b328cbb9e75f2d7686a992e554e4
      NOTE: Starting bitbake server...
      basehash changed from 2184b7365c1633ac3fb53b651942e4293a770d6baccf154988b92909ce7c4f7e to 33665fee96b9e6351c11b0597f2bcb035b565fd35d41f28bcf01ca7d6793031d
      Variable DEPENDS value changed:
      "cmake-native ${BASEDEPENDS}  {+snappy+} ninja-native"
      runtaskdeps changed:
      ['cmake-native:do_create_spdx gcc-cross-x86_64:do_create_spdx gcc-runtime:do_create_spdx glibc:do_create_spdx leveldb:do_unpack ninja-native:do_create_spdx', +snappy:do_create_spdx]
      Number of task dependencies changed
      Dependency on task snappy:do_create_spdx was added with hash 6a2f8b52a26d64e2a7370a53dc468c94ac0753a4e3585090ee666c1947dfa280

   leveldb:do_prepare_recipe_sysroot: 40af9c6d90ef25081a2b7f9981df47638626be4ff2317be9f3417f067c79f9e7 -> adcad39d9f6b8aa6a24973f3d25b899ac5bcc7acac8b0c6447cdba8d7e019b5f
      bitbake-diffsigs --task leveldb do_prepare_recipe_sysroot --signature 40af9c6d90ef25081a2b7f9981df47638626be4ff2317be9f3417f067c79f9e7 adcad39d9f6b8aa6a24973f3d25b899ac5bcc7acac8b0c6447cdba8d7e019b5f
      NOTE: Starting bitbake server...
      runtaskdeps changed:
      ['cmake-native:do_populate_sysroot gcc-cross-x86_64:do_populate_sysroot gcc-runtime:do_populate_sysroot glibc:do_populate_sysroot leveldb:do_fetch ninja-native:do_populate_sysroot pseudo-native:do_populate_sysroot', +snappy:do_populate_sysroot]
      Number of task dependencies changed
      Dependency on task snappy:do_populate_sysroot was added with hash ea7dcf450ca98566cbcd6c66b5c15c97df1d7da470ade427985d44d66b283aba

   libdrm:do_recipe_qa: 0bbb738248505f434805a3fb44758b7c9f9d3368a864248f94e64caaba7426dd -> d52392d300e27c5701e7c96212b1f8bff7636b993e859153b44f3a84352d76f1
      bitbake-diffsigs --task libdrm do_recipe_qa --signature 0bbb738248505f434805a3fb44758b7c9f9d3368a864248f94e64caaba7426dd d52392d300e27c5701e7c96212b1f8bff7636b993e859153b44f3a84352d76f1
      NOTE: Starting bitbake server...
      basehash changed from 6a667d1cfafc9b0ead937d3c2482f717474886ed2d29fc6960f338068d6e8813 to 75e4aa132468012b608f830d8f84573f4007cbd962a3267a92e419512e3523da
      Variable SRC_URI value changed:
      "http://dri.freedesktop.org/libdrm/${BP}.tar.xz            {+file://0001-tests-add-vboxvideo-to-tested-kernel-modules.patch+}"

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>