systemd: drop cgroupv2 PACKAGECONFIG
* The 'cgroupv2' PACKAGECONFIG is dropped as systemd now only supports
  cgroupv2 since 256 upgrade in:
  https://git.openembedded.org/openembedded-core/commit/?id=89b75b46371d5e9172cb496b461824d8551a2af5

* fixes:
  ERROR: QA Issue: systemd: invalid PACKAGECONFIG: cgroupv2 [invalid-packageconfig]

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>