wayland: ignore implicit-function-declaration issues
These are fatal by default with gcc-14.

wayland-1.22.0/src/wayland-util.c:456:64: error: implicit declaration of function 'getpid' [-Wimplicit-function-declaration]
wayland-1.22.0/src/wayland-util.c:456:74: error: implicit declaration of function 'pthread_self' [-Wimplicit-function-declaration]
caused by 0003-Enhance-Wayland-debug-print.patch

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>