webos-keyboard: use -std=gnu++14 instead of gcc-11 default -std=gnu++17 because of presage headers
* fixes:
In file included from ../../../git/src/lib/logic/languageplugininterface.h:7,
                 from ../../../git/src/lib/logic/wordengine.h:37,
                 from ../../../git/src/lib/logic/wordengine.cpp:32:
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:115:40: error: ISO C++17 does not allow dynamic exception specifications
  115 |     Presage(PresageCallback* callback) throw (PresageException);
      |                                        ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:125:66: error: ISO C++17 does not allow dynamic exception specifications
  125 |     Presage(PresageCallback* callback, const std::string config) throw (PresageException);
      |                                                                  ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:141:40: error: ISO C++17 does not allow dynamic exception specifications
  141 |     std::vector<std::string> predict() throw (PresageException);
      |                                        ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:156:81: error: ISO C++17 does not allow dynamic exception specifications
  156 |     std::multimap<double, std::string> predict(std::vector<std::string> filter) throw (PresageException);
      |                                                                                 ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:170:46: error: ISO C++17 does not allow dynamic exception specifications
  170 |     void learn(const std::string text) const throw (PresageException);
      |                                              ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:179:58: error: ISO C++17 does not allow dynamic exception specifications
  179 |     PresageCallback* callback(PresageCallback* callback) throw (PresageException);
      |                                                          ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:193:45: error: ISO C++17 does not allow dynamic exception specifications
  193 |     std::string completion(std::string str) throw (PresageException);
      |                                             ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:199:33: error: ISO C++17 does not allow dynamic exception specifications
  199 |     std::string context() const throw (PresageException);
      |                                 ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:206:33: error: ISO C++17 does not allow dynamic exception specifications
  206 |     bool context_change() const throw (PresageException);
      |                                 ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:212:32: error: ISO C++17 does not allow dynamic exception specifications
  212 |     std::string prefix() const throw (PresageException);
      |                                ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:221:58: error: ISO C++17 does not allow dynamic exception specifications
  221 |     std::string config(const std::string variable) const throw (PresageException);
      |                                                          ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:230:76: error: ISO C++17 does not allow dynamic exception specifications
  230 |     void config(const std::string variable, const std::string value) const throw (PresageException);
      |                                                                            ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:239:30: error: ISO C++17 does not allow dynamic exception specifications
  239 |     void save_config() const throw (PresageException);
      |                              ^~~~~
make[2]: *** [Makefile:3747: wordengine.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from ../../../git/src/lib/logic/languageplugininterface.h:7,
                 from ../../../git/src/lib/logic/wordengine.h:37,
                 from moc_wordengine.cpp:10:
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:115:40: error: ISO C++17 does not allow dynamic exception specifications
  115 |     Presage(PresageCallback* callback) throw (PresageException);
      |                                        ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:125:66: error: ISO C++17 does not allow dynamic exception specifications
  125 |     Presage(PresageCallback* callback, const std::string config) throw (PresageException);
      |                                                                  ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:141:40: error: ISO C++17 does not allow dynamic exception specifications
  141 |     std::vector<std::string> predict() throw (PresageException);
      |                                        ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:156:81: error: ISO C++17 does not allow dynamic exception specifications
  156 |     std::multimap<double, std::string> predict(std::vector<std::string> filter) throw (PresageException);
      |                                                                                 ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:170:46: error: ISO C++17 does not allow dynamic exception specifications
  170 |     void learn(const std::string text) const throw (PresageException);
      |                                              ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:179:58: error: ISO C++17 does not allow dynamic exception specifications
  179 |     PresageCallback* callback(PresageCallback* callback) throw (PresageException);
      |                                                          ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:193:45: error: ISO C++17 does not allow dynamic exception specifications
  193 |     std::string completion(std::string str) throw (PresageException);
      |                                             ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:199:33: error: ISO C++17 does not allow dynamic exception specifications
  199 |     std::string context() const throw (PresageException);
      |                                 ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:206:33: error: ISO C++17 does not allow dynamic exception specifications
  206 |     bool context_change() const throw (PresageException);
      |                                 ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:212:32: error: ISO C++17 does not allow dynamic exception specifications
  212 |     std::string prefix() const throw (PresageException);
      |                                ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:221:58: error: ISO C++17 does not allow dynamic exception specifications
  221 |     std::string config(const std::string variable) const throw (PresageException);
      |                                                          ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:230:76: error: ISO C++17 does not allow dynamic exception specifications
  230 |     void config(const std::string variable, const std::string value) const throw (PresageException);
      |                                                                            ^~~~~
/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/recipe-sysroot/usr/include/presage.h:239:30: error: ISO C++17 does not allow dynamic exception specifications
  239 |     void save_config() const throw (PresageException);
      |                              ^~~~~
make[2]: *** [Makefile:4150: moc_wordengine.o] Error 1
make[2]: Leaving directory '/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/build/src/lib'
make[1]: *** [Makefile:49: sub-lib-make_first-ordered] Error 2
make[1]: Leaving directory '/OE/build/luneos-honister/webos-ports/tmp-glibc/work/core2-64-webos-linux/webos-keyboard/0.99.2+gitAUTOINC+053037137e-r0/build/src'
make: *** [Makefile:50: sub-src-make_first-ordered] Error 2

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>