bluebinder: switch to MACHINE_ARCH
* fixes:
  ERROR: bluebinder different signature for task do_package_write_ipk.sigdata between hammerhead and mako
  Hash for dependent task android-property-service/android-property-service.bb:do_packagedata changed from f400669d3fab0c5e73902f700fe9f5780dd9065c355095911f4db6cd2cab78e3 to ea72f74d9eaf1b98180a7405e1b3f9d3523ce4f563207832fc64a9a1032bc410
  Unable to find matching sigdata for /home/jenkins/workspace/luneos-testing/webos-ports/meta-webos-ports/meta-luneos/recipes-android/android-property-service/android-property-service.bb:do_packagedata with hashes f400669d3fab0c5e73902f700fe9f5780dd9065c355095911f4db6cd2cab78e3 or ea72f74d9eaf1b98180a7405e1b3f9d3523ce4f563207832fc64a9a1032bc410

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>