sdl2-opengles-test: build only sdl2_opengles2_test for all rpi MACHINEs
* fixes:
bitbake-diffsigs tmp-glibc/sstate-diff/1555495762/r*/*/sdl2-opengles-test/*do_compile*
NOTE: Starting bitbake server...
basehash changed from fcf3a17ce5321dd1d38448a6b19a59ad680a85a8b1bee7560e8e0c373eb6c65b to 6aaf9561351ce3371f01de564e7ab970333456bb319e8dc8f093a247eb2640fc
Variable TARGETS value changed:
"[-sdl2_opengles1_test-] sdl2_opengles2_test"

 === Comparing signatures for task do_populate_sysroot.sigdata between raspberrypi2 and raspberrypi3 ===
ERROR: sdl2-opengles-test different signature for task do_populate_sysroot.sigdata between raspberrypi2 and raspberrypi3
NOTE: Starting bitbake server...
Hash for dependent task sdl2-opengles-test/sdl2-opengles-test_git.bb.do_install changed from dd9a09d46ac871ccb2c0acdb881c1941153ab8f21258d0d41f6ba6ca73462526 to e21766ff7f16
1063d59a72a8d040cc7acef7edfb73d5f6ce71097a66db3c82ec
Unable to find matching sigdata for /OE/build/luneos-master/webos-ports/meta-webos-ports/meta-luneos/recipes-graphics/sdl2-opengles-test/sdl2-opengles-test_git.bb.do_install
 with hashes dd9a09d46ac871ccb2c0acdb881c1941153ab8f21258d0d41f6ba6ca73462526 or e21766ff7f161063d59a72a8d040cc7acef7edfb73d5f6ce71097a66db3c82ec

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>