mesa-gl: remove ${includedir}/KHR/khrplatform.h when using libhybris
* like rpi does in meta-raspberrypi we need to resolve conflict between
  mesa-gl and libhybris, e.g. when building weston for tissot:
  ERROR: weston-5.0.0-r0 do_prepare_recipe_sysroot: The file /usr/include/KHR/khrplatform.h is installed by both mesa-gl and libhybris, aborting

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>