meta-luneos: BBMASK nativesdk-packagegroup-qt6-toolchain-host* because of inherit_defer
* nativesdk-packagegroup-qt6-toolchain-host.bb inherits nativesdk, but after:
  https://git.openembedded.org/openembedded-core/diff/meta/classes-recipe/packagegroup.bbclass?id=451363438d38bd4552d5bcec4a92332f5819a5d4
  it's no longer the last inherit, because allarch from packagegroup is inherit_defer causing:

  ERROR: /OE/build/luneos-scarthgap/meta-qt6/recipes-qt/packagegroups/nativesdk-packagegroup-qt6-toolchain-host.bb: QA Issue: nativesdk-packagegroup-qt6-toolchain-host: native/nativesdk class is not inherited last, this can result in unexpected behaviour. Classes inherited after native/nativesdk: allarch.bbclass [native-last]
  ERROR: /OE/build/luneos-scarthgap/meta-qt6/recipes-qt/packagegroups/nativesdk-packagegroup-qt6-toolchain-host.bb: Fatal QA errors were found, failing task.

  we don't use nativesdk so we can just BBMASK it here, until TQC figures out
  how to support multiple OE releases from the same branch as e.g.:
  https://code.qt.io/cgit/yocto/meta-qt6.git/tree/conf/layer.conf has:
  LAYERSERIES_COMPAT_qt6-layer = "kirkstone langdale mickledore nanbield"
  but doesn't even parse with scarthgap now and fixing it with inherit_defer
  for nativesdk won't be compatible with nanbield and older as it was only added in:
  https://git.openembedded.org/bitbake/commit/?id=5c2e840eafeba1f0f754c226b87bfb674f7bea29

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>