alsa-ucm-conf: add missing Upstream-Status
* fixes:
  ERROR: QA Issue: Missing Upstream-Status in patch
  /OE/build/luneos-scarthgap/meta-webos-ports/meta-luneos/recipes-multimedia/alsa/alsa-ucm-conf/0007-Fix-UCM-for-RK817.patch
  Please add according to https://docs.yoctoproject.org/contributor-guide/recipe-style-guide.html#patch-upstream-status . [patch-status]

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>