wpa-supplicant: ignore implicit-function-declaration issues
These are fatal by default with gcc-14.

caused by 0001-Add-p2p-changes.patch
notify.c:769:25: error: implicit declaration of function 'wpas_dbus_signal_p2p_peer_joined_with_ip'; did you mean 'wpas_dbus_signal_p2p_peer_joined'? [-Wimplicit-function-declaration]

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>