pmcertificatemgr: drop webos_machine_impl_dep inherit
* it's used only for:
if(${WEBOS_TARGET_MACHINE_IMPL} STREQUAL simulator)
        webos_add_compiler_flags(ALL  -fno-exceptions)
        webos_add_linker_options(ALL  -fno-exceptions)
endif()
  and we never used simulator in webos-ports, so drop this
  to fix certmgr depending on this MACHINE_ARCH recipe causing:

ERROR: certmgrd different signature for task do_configure.sigdata between hammerhead and mako
runtaskdeps changed:
certmgrd/certmgrd.bb.do_prepare_recipe_sysroot with hash 5fddf18d82054abc721a53a80c4e68d7
 changed to
certmgrd/certmgrd.bb.do_prepare_recipe_sysroot with hash 3931690d0b67bd78f644bee37703dce2
Hash for dependent task certmgrd/certmgrd.bb.do_prepare_recipe_sysroot changed from 5fddf18d82054abc721a53a80c4e68d7 to 3931690d0b67bd78f644bee37703dce2

  as detected in:
  http://jenkins.nas-admin.org/view/luneos-testing/job/luneos-testing_workspace-compare-signatures/11/console

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>