com.webos.app.camera: chown root:root work around pseudo/libuv/nodejs issue WRR-13760
As reported in:
https://lists.openembedded.org/g/openembedded-devel/message/114223
https://lists.openembedded.org/g/openembedded-devel/message/114226

new nodejs re-introduces the issue again.

But this time my old reproducer com.webos.app.minimal in https://git.openembedded.org/meta-openembedded-contrib/log/?h=jansa/master no longer triggers this issue

It can be reproduced with e.g. com.webos.app.camera

http://gecko.lge.com:8000/Errors/Details/1043452

ERROR: com.webos.app.camera-0.0.1-18-r3 do_package_qa: QA Issue: com.webos.app.camera: /usr/palm/applications/com.webos.app.camera/Icons/Back.svg
is owned by uid 1000, which is the same as the user running bitbake. This may be due to host contamination [host-user-contaminated]
with bitbake executed by uid 1000 (which does exist in base-passwd)

or http://gecko.lge.com:8000/Errors/Details/1044757

ERROR: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:sstate_report_unihash(d)
     0003:
File: 'TOPDIR/oe-core/meta/classes-global/sstate.bbclass', lineno: 909, function: sstate_report_unihash
     0905:    report_unihash = getattr(bb.parse.siggen, 'report_unihash', None)
     0906:
     0907:    if report_unihash:
     0908:        ss = sstate_state_fromvars(d)
 *** 0909:        report_unihash(os.getcwd(), ss['task'], d)
     0910:}
     0911:
     0912:#
     0913:# Shell function to decompress and prepare a package for installation
File: 'TOPDIR/bitbake/lib/bb/siggen.py', lineno: 784, function: report_unihash
     0780:
     0781:            if "." in self.method:
     0782:                (module, method) = self.method.rsplit('.', 1)
     0783:                locs['method'] = getattr(importlib.import_module(module), method)
 *** 0784:                outhash = bb.utils.better_eval('method(path, sigfile, task, d)', locs)
     0785:            else:
     0786:                outhash = bb.utils.better_eval(self.method + '(path, sigfile, task, d)', locs)
     0787:
     0788:            try:
File: 'TOPDIR/bitbake/lib/bb/utils.py', lineno: 434, function: better_eval
     0430:    if extraglobals:
     0431:        ctx = copy.copy(ctx)
     0432:        for g in extraglobals:
     0433:            ctx[g] = extraglobals[g]
 *** 0434:    return eval(source, ctx, locals)
     0435:
     0436:@contextmanager
     0437:def fileslocked(files, *args, **kwargs):
     0438:    """Context manager for locking and unlocking file locks."""
File: '<string>', lineno: 1, function: <module>
  File "<string>", line 1, in <module>

File: 'TOPDIR/oe-core/meta/lib/oe/sstatesig.py', lineno: 721, function: OEOuthashBasic
     0717:                process(root)
     0718:            for f in files:
     0719:                if f == 'fixmepath':
     0720:                    continue
 *** 0721:                process(os.path.join(root, f))
     0722:
     0723:            for dir in dirs:
     0724:                if os.path.islink(os.path.join(root, dir)):
     0725:                    process(os.path.join(root, dir))
File: 'TOPDIR/oe-core/meta/lib/oe/sstatesig.py', lineno: 656, function: process
     0652:                    except KeyError as e:
     0653:                        msg = ("KeyError: %s\nPath %s is owned by uid %d, gid %d, which doesn't match "
     0654:                            "any user/group on target. This may be due to host contamination." %
     0655:                            (e, os.path.abspath(path), s.st_uid, s.st_gid))
 *** 0656:                        raise Exception(msg).with_traceback(e.__traceback__)
     0657:
     0658:                if include_timestamps:
     0659:                    # Need to clamp to SOURCE_DATE_EPOCH
     0660:                    if s.st_mtime > source_date_epoch:
File: 'TOPDIR/oe-core/meta/lib/oe/sstatesig.py', lineno: 650, function: process
     0646:                    else:
     0647:                        add_perm(stat.S_IXOTH, 'x')
     0648:
     0649:                    try:
 *** 0650:                        update_hash(" %10s" % pwd.getpwuid(s.st_uid).pw_name)
     0651:                        update_hash(" %10s" % grp.getgrgid(s.st_gid).gr_name)
     0652:                    except KeyError as e:
     0653:                        msg = ("KeyError: %s\nPath %s is owned by uid %d, gid %d, which doesn't match "
     0654:                            "any user/group on target. This may be due to host contamination." %
Exception: Exception: KeyError: 'getpwuid(): uid not found: 1026'
Path TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/sstate-build-package/package/usr/palm/applications/com.webos.app.camera/Icons/Back.svg is owned by uid 1026, gid 1026, which doesn't match any user/group on target. This may be due to host contamination.
When bitbake is executed by uid which doesn't exist in base-passwd (e.g. 1026 used in my docker builds).

Interestingly there are 2 identical Back.svg files (in Icons and public/Icons) and the one in public/Icons seems to work fine:

sqlite3 /OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/pseudo/files.db "select * from files" | grep Back.svg
20|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/image/usr/palm/applications/com.webos.app.camera/public/Icons/Back.svg|66310|211321360|0|0|33188|0|0
209|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/image/usr/palm/applications/com.webos.app.camera/Icons/Back.svg|66310|211462623|1026|1026|33188|0|0
389|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/sstate-build-package/package/usr/palm/applications/com.webos.app.camera/Icons/Back.svg|66310|211725698|1026|1026|33188|0|0
442|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/sstate-build-package/package/usr/palm/applications/com.webos.app.camera/public/Icons/Back.svg|66310|211725752|0|0|33188|0|0
581|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/sstate-build-package/packages-split/com.webos.app.camera/usr/palm/applications/com.webos.app.camera/Icons/Back.svg|66310|211725698|1026|1026
|33188|0|0
668|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/sstate-build-package/packages-split/com.webos.app.camera/usr/palm/applications/com.webos.app.camera/public/Icons/Back.svg|66310|211725752|0|
0|33188|0|0
But I don't understand why 2nd copy of all the Icons was created, the only difference is PTZIcon.svg and PTZIcon180.svg

com.webos.app.camera/0.0.1-18/image $ diff -rq usr/palm/applications/com.webos.app.camera/Icons/ usr/palm/applications/com.webos.app.camera/public/Icons/
Only in usr/palm/applications/com.webos.app.camera/Icons/: PTZIcon180.svg
Only in usr/palm/applications/com.webos.app.camera/Icons/: PTZIcon.svg
The Back.svg is used like many other icons:

com.webos.app.camera/0.0.1-18/git $ git grep import.*svg
src/components/CameraPreview.js:import fullscreenIcon from '../../public/Icons/full screen.svg';
src/components/CameraPreview.js:import stopRecordIcon from '../../public/Icons/StopRecording.svg';
src/components/CameraPreview.js:import recordingIcon from '../../public/Icons/recording.svg';
src/components/CameraPreview.js:import startRecordIcon from '../../public/Icons/StarRecording.svg';
src/components/CameraPreview.js:import snapshoIcon from '../../public/Icons/snapshot.svg';
src/components/PTZControl/PTZControl.js:import PTZ_Disable from '../../../public/Icons/PTZ_Disable.svg';
src/components/Settings/Settings.js:import closeIcon from '../../../public/Icons/Close.svg';
src/views/Footer/Footer.js:import refreshIcon from '../../../public/Icons/refresh.svg';
src/views/Footer/Footer.js:import power_on from '../../../public/Icons/power_on.svg';
src/views/Footer/Footer.js:import power_off from '../../../public/Icons/power_off.svg';
src/views/Footer/Footer.js:import startRecordIcon from '../../../public/Icons/StarRecording.svg';
src/views/Footer/Footer.js:import stopRecordIcon from '../../../public/Icons/StopRecording.svg';
src/views/Footer/Footer.js:import snapshoIcon from '../../../public/Icons/snapshot.svg';
src/views/Footer/Footer.js:import videoPlayerIcon from '../../../public/Icons/Video player.svg';
src/views/Footer/Footer.js:import imagePlayerIcon from '../../../public/Icons/Image viewer.svg';
src/views/FullScreenPreview/FullScreenPreview.js:import backIcon from '../../../public/Icons/Back.svg';
src/views/FullScreenPreview/FullScreenPreview.js:import recordingIcon from '../../../public/Icons/recording.svg';
src/views/FullScreenPreview/FullScreenPreview.js:import videoPlayerIcon from '../../../public/Icons/Video player.svg';
src/views/FullScreenPreview/FullScreenPreview.js:import imagePlayerIcon from '../../../public/Icons/Image viewer.svg';
src/views/FullScreenPreview/FullScreenPreview.js:import snapshoIcon from '../../../public/Icons/snapshot.svg';
src/views/FullScreenPreview/FullScreenPreview.js:import stopRecordIcon from '../../../public/Icons/StopRecording.svg';
src/views/FullScreenPreview/FullScreenPreview.js:import StarRecording from '../../../public/Icons/StarRecording.svg';
src/views/FullScreenPreview/FullScreenPreview.js:import settingsIcon from '../../../public/Icons/settings.svg';
someone with experience with enact or webpack might be able to resolve this faster.

I've verified that reverting the libuv upgrade in nodejs avoids this issue again:

martin@jama /OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera $ sqlite3 0.0.1-18.new-nodejs-older-libuv-pseudo-debug/pseudo/files.db "select * from files" | grep Back.svg
38|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/image/usr/palm/applications/com.webos.app.camera/public/Icons/Back.svg|66310|195205234|0|0|33188|0|0
209|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/image/usr/palm/applications/com.webos.app.camera/Icons/Back.svg|66310|199939990|0|0|33188|0|0
389|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/package/usr/palm/applications/com.webos.app.camera/Icons/Back.svg|66310|239614072|0|0|33188|0|0
442|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/package/usr/palm/applications/com.webos.app.camera/public/Icons/Back.svg|66310|240794224|0|0|33188|0|0
581|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/packages-split/com.webos.app.camera/usr/palm/applications/com.webos.app.camera/Icons/Back.svg|66310|239614072|0|0|33188|0|0
668|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/packages-split/com.webos.app.camera/usr/palm/applications/com.webos.app.camera/public/Icons/Back.svg|66310|240794224|0|0|33188|0|0

martin@jama /OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera $ sqlite3 0.0.1-18.new-nodejs-pseudo-debug/pseudo/files.db "select * from files" | grep Back.svg
33|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/image/usr/palm/applications/com.webos.app.camera/public/Icons/Back.svg|66310|193887995|0|0|33188|0|0
209|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/image/usr/palm/applications/com.webos.app.camera/Icons/Back.svg|66310|194256047|1026|1026|33188|0|0
389|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/sstate-build-package/package/usr/palm/applications/com.webos.app.camera/Icons/Back.svg|66310|207146886|1026|1026|33188|0|0
442|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/sstate-build-package/package/usr/palm/applications/com.webos.app.camera/public/Icons/Back.svg|66310|207146939|0|0|33188|0|0
581|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/sstate-build-package/packages-split/com.webos.app.camera/usr/palm/applications/com.webos.app.camera/Icons/Back.svg|66310|207146886|1026|1026|33188|0|0
668|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/sstate-build-package/packages-split/com.webos.app.camera/usr/palm/applications/com.webos.app.camera/public/Icons/Back.svg|66310|207146939|0|0|33188|0|0

martin@jama /OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera $ sqlite3 0.0.1-18.new-nodejs/pseudo/files.db "select * from files" | grep Back.svg
30|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/image/usr/palm/applications/com.webos.app.camera/public/Icons/Back.svg|66310|194286069|0|0|33188|0|0
209|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/image/usr/palm/applications/com.webos.app.camera/Icons/Back.svg|66310|194286249|0|0|33188|0|0
389|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/package/usr/palm/applications/com.webos.app.camera/Icons/Back.svg|66310|194410786|0|0|33188|0|0
442|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/package/usr/palm/applications/com.webos.app.camera/public/Icons/Back.svg|66310|194411631|0|0|33188|0|0
581|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/packages-split/com.webos.app.camera/usr/palm/applications/com.webos.app.camera/Icons/Back.svg|66310|194410786|0|0|33188|0|0
668|/OE/lge/build/webos/walnascar/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-18/packages-split/com.webos.app.camera/usr/palm/applications/com.webos.app.camera/public/Icons/Back.svg|66310|194411631|0|0|33188|0|0

[WRR-13760] host-user-contaminated with new nodejs-22.12.0

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>