wam: Fix build with gcc-13
Ignore overloaded-virtual issues for now to work around:
FAILED: src/plugin/CMakeFiles/webappmgr-default-plugin.dir/web_app_factory_luna.cc.o
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++ -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBO
OST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -Dwebappmgr_default_plugin_EXPORTS -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot/usr/include/webrunti
me -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/core -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/platform -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/platform/webengine -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/util -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot/usr/include/json-c -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/webos -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2  --sysroot=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git=/usr/src/debug/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30  -fdebug-prefix-map=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git=/usr/src/debug/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30  -fmacro-prefix-map=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/build=/usr/src/debug/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30  -fdebug-prefix-map=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/build=/usr/src/debug/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30  -fdebug-prefix-map=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot=  -fmacro-prefix-map=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot=  -fdebug-prefix-map=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot-native=  -fvisibility-inlines-hidden -Wno-error=uninitialized -Wno-error=maybe-uninitialized -fno-rtti -fno-exceptions -Wall -fpermissive -funwind-tables -std=c++14 -Wno-psabi -Werror -DNDEBUG -fPIC -std=gnu++14 -MD -MT src/plugin/CMakeFiles/webappmgr-default-plugin.dir/web_app_factory_luna.cc.o -MF src/plugin/CMakeFiles/webappmgr-default-plugin.dir/web_app_factory_luna.cc.o.d -o src/plugin/CMakeFiles/webappmgr-default-plugin.dir/web_app_factory_luna.cc.o -c /OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/plugin/web_app_factory_luna.cc
In file included from /OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/platform/web_app_wayland.h:28,
                 from /OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/plugin/web_app_factory_luna.cc:25:
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/util/timer.h: In instantiation of 'class BaseTimer<WebAppWayland, false>':
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/util/timer.h:77:7:   required from 'class OneShotTimer<WebAppWayland>'
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/platform/web_app_wayland.h:177:31:   required from here
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/util/timer.h:30:16: error: 'virtual void Timer::Start(int, bool)' was hidden [-Werror=overloaded-virtual=]
   30 |   virtual void Start(int delay_in_milli_seconds, bool will_destroy = false);
      |                ^~~~~
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/util/timer.h:62:8: note:   by 'void BaseTimer<Receiver, kIsRepeating>::Start(int, Receiver*, ReceiverMethod, bool) [with Receiver = WebAppWayland; bool kIsRepeating = false; ReceiverMethod = void (WebAppWayland::*)()]'
   62 |   void Start(int delay_in_milli_seconds,
      |        ^~~~~
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/util/timer.h: In instantiation of 'class BaseTimer<WebPageBlink, false>':
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/util/timer.h:77:7:   required from 'class OneShotTimer<WebPageBlink>'
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/platform/webengine/web_page_blink.h:211:30:   required from here
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/util/timer.h:30:16: error: 'virtual void Timer::Start(int, bool)' was hidden [-Werror=overloaded-virtual=]
   30 |   virtual void Start(int delay_in_milli_seconds, bool will_destroy = false);
      |                ^~~~~
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/util/timer.h:62:8: note:   by 'void BaseTimer<Receiver, kIsRepeating>::Start(int, Receiver*, ReceiverMethod, bool) [with Receiver = WebPageBlink; bool kIsRepeating = false; ReceiverMethod = void (WebPageBlink::*)()]'
   62 |   void Start(int delay_in_milli_seconds,
      |        ^~~~~
cc1plus: all warnings being treated as errors

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>