meta-luneui: add clang-layer to LAYERDEPENDS
* libpbnjson-clang in meta-luneui depends on clang:

  ERROR: Nothing PROVIDES 'clang' (but /OE/build/oe-core/meta-webos-ports/meta-luneui/recipes-webos-ose/libpbnjson/libpbnjson-clang.bb DEPENDS on or otherwise requires it). Close matches:
    slang
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'libpbnjson-clang', 'clang']

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>