webos-connman-adapter: use gnu17 even with gcc-15
gcc-15 uses gnu23 standard for c since:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212
but this component isn't readly for it and fails to build.

webos-connman-adapter/1.1.0-242.apollo.18/git/src/main.c:47:5: error: conflicting types for 'initialize_wifi_ls2_calls'; have 'int(void)'
webos-connman-adapter/1.1.0-242.apollo.18/git/src/main.c:86:13: error: too many arguments to function 'initialize_wifi_ls2_calls'; expected 0, have 2

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>