cordova: inherit allarch
* it doesn't seem to be machine or architecture specific, use allarch to
  fix:
ERROR: org.webosports.app.calculator different signature for task do_package_write_ipk.sigdata between hammerhead and qemux86
runtaskdeps changed:
cordova/cordova_2.3.0.bb.do_packagedata with hash 08fd1c1a4add97c774c193562099ff6d
 changed to
cordova/cordova_2.3.0.bb.do_packagedata with hash 86a30608b525ba4f3d19288441071154
Hash for dependent task cordova/cordova_2.3.0.bb.do_packagedata changed from 08fd1c1a4add97c774c193562099ff6d to 86a30608b525ba4f3d19288441071154

as detected in:
http://jenkins.nas-admin.org/view/luneos-testing/job/luneos-testing_workspace-compare-signatures/11/console

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>