luneos-preferred-versions.inc: adjust libgpiod version
WARNING: preferred version 1.6.4 of libgpiod not available (for item libgpiod)
WARNING: versions of libgpiod available: 1.6.5 2.2.1
WARNING: preferred version 1.6.4 of libgpiod not available (for item libgpiod-manager)
WARNING: versions of libgpiod available: 2.2.1
WARNING: preferred version 1.6.4 of libgpiod not available (for item libgpiod-dev)
WARNING: versions of libgpiod available: 1.6.5 2.2.1
WARNING: preferred version 1.6.4 of libgpiod not available (for item libgpiod-manager-cfg)
WARNING: versions of libgpiod available: 2.2.1
WARNING: preferred version 1.6.4 of libgpiod not available (for item libgpiod)
WARNING: versions of libgpiod available: 1.6.5 2.2.1

and eg25-manager still fails with newer 2.2.1 (which is used by default)

luneos-whinlatter $ grep error: /OE/build/luneos-whinlatter/tmp/work/aarch64-webos-linux/eg25-manager/0.4.2-1+git/temp/log.do_compile.398685
../sources/eg25-manager-0.4.2-1+git/src/gpio.c:45:5: error: implicit declaration of function 'gpiod_line_set_value'; did you mean 'g_key_file_set_value'? [-Wimplicit-function-declaration]
../sources/eg25-manager-0.4.2-1+git/src/gpio.c:84:9: error: implicit declaration of function 'gpiod_line_get_value'; did you mean 'g_key_file_get_value'? [-Wimplicit-function-declaration]
../sources/eg25-manager-0.4.2-1+git/src/gpio.c:108:17: error: implicit declaration of function 'gpiod_chip_get_line'; did you mean 'gpiod_chip_get_info'? [-Wimplicit-function-declaration]
../sources/eg25-manager-0.4.2-1+git/src/gpio.c:108:15: error: assignment to 'struct gpiod_line *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
../sources/eg25-manager-0.4.2-1+git/src/gpio.c:112:9: error: implicit declaration of function 'gpiod_line_request_output'; did you mean 'gpiod_line_request_get_fd'? [-Wimplicit-function-declaration]
../sources/eg25-manager-0.4.2-1+git/src/gpio.c:113:9: error: implicit declaration of function 'gpiod_line_release'; did you mean 'gpiod_line_request_release'? [-Wimplicit-function-declaration]
../sources/eg25-manager-0.4.2-1+git/src/gpio.c:124:15: error: assignment to 'struct gpiod_line *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
../sources/eg25-manager-0.4.2-1+git/src/gpio.c:128:9: error: implicit declaration of function 'gpiod_line_request_input'; did you mean 'gpiod_line_request_get_fd'? [-Wimplicit-function-declaration]
../sources/eg25-manager-0.4.2-1+git/src/gpio.c:172:36: error: implicit declaration of function 'gpiod_chip_open_by_label'; did you mean 'gpiod_chip_info_get_label'? [-Wimplicit-function-declaration]
../sources/eg25-manager-0.4.2-1+git/src/gpio.c:172:34: error: assignment to 'struct gpiod_chip *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
../sources/eg25-manager-0.4.2-1+git/src/gpio.c:188:56: error: implicit declaration of function 'gpiod_chip_num_lines'; did you mean 'gpiod_chip_request_lines'? [-Wimplicit-function-declaration]
../sources/eg25-manager-0.4.2-1+git/src/gpio.c:218:30: error: assignment to 'struct gpiod_chip *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
../sources/eg25-manager-0.4.2-1+git/src/gpio.c:222:30: error: assignment to 'struct gpiod_chip *' from 'int' makes pointer from integer without a cast [-Wint-conversion]

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>