webos-initscripts: don't include systemd-machine-units in sstate signature
* systemd-machine-units is MACHINE_ARCH, but webos-initscripts isn't
  ERROR: webos-initscripts different signature for task do_package_write_ipk.sigdata between hammerhead and mako
  NOTE: Starting bitbake server...
  Hash for dependent task systemd/systemd-machine-units_1.0.bb.do_packagedata changed from 1bdbbdd14c36b73d5dd9996f38d0148fb769162ceaba7fed2a2a974e27253d0b to 2722d496fb3286c57af851ba168813c09952c31babbdb0bc8cd47f0c057aa419
  Unable to find matching sigdata for /OE/build/luneos-master/webos-ports/openembedded-core/meta/recipes-core/systemd/systemd-machine-units_1.0.bb.do_packagedata with hashes 1bdbbdd14c36b73d5dd9996f38d0148fb769162ceaba7fed2a2a974e27253d0b or 2722d496fb3286c57af851ba168813c09952c31babbdb0bc8cd47f0c057aa419

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>