connman, (webos-)connman-adapter: import from separate meta-webos-ports
* for history check danny-old branch

* changes since import:
* webos-connman-adapter: add temporary patch to fix #379
  Patch will go upstream and should be dropped once it is included upstream.
* connman-conf: add wired-setup script to SRC_URI
* connman-conf: fix build for qemu*
  qemuall append without leading space, which causes errors like this:
  ERROR: Fetcher failure: Unable to find file file://wired-setupfile://wired.config anywhere.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>