wam: Fix build with gcc-13 II
* fix overloaded-virtual properly, because
  -Wno-error=overloaded-virtual= is not supported in gcc-12 and older

* but there is one more overloaded-virtual issue for which I'll need
  to update webruntime again:

FAILED: src/platform/CMakeFiles/WebAppMgr.dir/web_app_wayland_window.cc.o
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++ -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DWebAppMgr_EXPORTS -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot/usr/include/webruntime -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/platform -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/platform/webengine -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot/usr/include/json-c -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/core -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/util -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/webos -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2  --sysroot=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git=/usr/src/debug/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30  -fdebug-prefix-map=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git=/usr/src/debug/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30  -fmacro-prefix-map=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/build=/usr/src/debug/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30  -fdebug-prefix-map=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/build=/usr/src/debug/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30  -fdebug-prefix-map=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot=  -fmacro-prefix-map=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot=  -fdebug-prefix-map=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot-native=  -fvisibility-inlines-hidden -Wno-error=uninitialized -Wno-error=maybe-uninitialized -fno-rtti -fno-exceptions -Wall -fpermissive -funwind-tables -std=c++14 -Wno-psabi -Werror -DNDEBUG -fPIC -std=gnu++14 -MD -MT src/platform/CMakeFiles/WebAppMgr.dir/web_app_wayland_window.cc.o -MF src/platform/CMakeFiles/WebAppMgr.dir/web_app_wayland_window.cc.o.d -o src/platform/CMakeFiles/WebAppMgr.dir/web_app_wayland_window.cc.o -c /OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/platform/web_app_wayland_window.cc
In file included from /OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot/usr/include/webruntime/webos/webapp_window_base.h:24,
                 from /OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/platform/web_app_wayland_window.h:20,
                 from /OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/git/src/platform/web_app_wayland_window.cc:17:
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot/usr/include/webruntime/neva/app_runtime/public/webapp_window_delegate.h:34:16: error: 'virtual bool neva_app_runtime::WebAppWindowDelegate::HandleEvent(neva_app_runtime::AppRuntimeEvent*)' was hidden [-Werror=overloaded-virtual=]
   34 |   virtual bool HandleEvent(AppRuntimeEvent* e);
      |                ^~~~~~~~~~~
In file included from /OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot/usr/include/webruntime/webos/webapp_window_base.h:30:
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/wam/1.0.2-55+gitAUTOINC+f8c30d3d79-r30/recipe-sysroot/usr/include/webruntime/webos/webapp_window_delegate.h:40:16: note:   by 'virtual bool webos::WebAppWindowDelegate::HandleEvent(WebOSEvent*)'
   40 |   virtual bool HandleEvent(WebOSEvent* e);
      |                ^~~~~~~~~~~
cc1plus: all warnings being treated as errors

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>