libofonobinderpluginext, libqofonoext: fix LIC_FILES_CHKSUM
Use path relative to S.

Use LICENSE.LGPL file added in 2021:
https://github.com/sailfishos/libqofonoext/commit/7c6e7a734e42367e24ecee02ab2735eb5678586b

instead of /src/qofonoext.cpp file where Copyright years
were changed in the same commit and LIC_FILES_CHKSUM md5 doesn't
match.

ERROR: QA Issue: libqofonoext: The LIC_FILES_CHKSUM does not match for file://src/qofonoext.cpp;;beginline=1;endline=14;md5=e78738e9230b2e0f55eb7f63e3444df5
libqofonoext: The new md5 checksum is 7f93bc26df022fa5dca0da094cc63e87
libqofonoext: Here is the selected license text:
vvvvvvvvvvvvvvvvvvvvvvvvvvvv beginline=1 vvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/****************************************************************************
**
** Copyright (C) 2015-2021 Jolla Ltd.
** Copyright (C) 2015-2021 Slava Monich <slava.monich@jolla.com>
**
** GNU Lesser General Public License Usage
** Alternatively, this file may be used under the terms of the GNU Lesser
** General Public License version 2.1 as published by the Free Software
** Foundation and appearing in the file LICENSE.LGPL included in the
** packaging of this file.  Please review the following information to
** ensure the GNU Lesser General Public License version 2.1 requirements
** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
**
****************************************************************************/
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ endline=14 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libqofonoext: Check if the license information has changed in /OE/build/luneos-whinlatter/tmp/work/corei7-64-webos-linux/libqofonoext/1.029+git/sources/libqofonoext-1.029+git/src/qofonoext.cpp (lines 1 through to 14) to verify that the LICENSE value "LGPL-2.1-only" remains valid [license-checksum]
ERROR: Fatal QA errors were found, failing task.

This file is LGPL-2.1-or-later instead of LGPL-2.1-only used in the
file headers before, adjust LICENSE.

It still fails to build this fixes just the populate_lic issue.

 cd src/ && ( test -e Makefile || /OE/build/luneos-whinlatter/tmp/work/corei7-64-webos-linux/libqofonoext/1.029+git/recipe-sysroot-native/usr/bin/qmake -o Makefile /OE/build/luneos-whinlatter/tmp/work/corei7-64-webos-linux/libqofonoext/1.029+git/sources/libqofonoext-1.029+git/src/src.pro ) && make -f Makefile
| Project ERROR: qofono-qt5 development package not found

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>