node-gyp-native: fix incorrect symlink
* when node-gyp-native is built there is a few relative symlinks:
  1) ${bindir}/node-gyp:
  OE @ ~/build/owpb/webos-ports/tmp-glibc/work/x86_64-linux/node-gyp-native/4.0.0+gitAUTOINC+7245415296-r0 $ ll sysroot-destdir/OE/build/owpb/webos-ports/tmp-glibc/work/x86_64-linux/node-gyp-native/4.0.0+gitAUTOINC+7245415296-r0/recipe-sysroot-native/usr/bin/node-gyp
  lrwxrwxrwx 2 bitbake bitbake 44 Sep 12 01:13 sysroot-destdir/OE/build/owpb/webos-ports/tmp-glibc/work/x86_64-linux/node-gyp-native/4.0.0+gitAUTOINC+7245415296-r0/recipe-sysroot-native/usr/bin/node-gyp -> ../lib/node_modules/node-gyp/bin/node-gyp.js*

  2) node_modules
  OE @ ~/build/owpb/webos-ports/tmp-glibc/work/x86_64-linux/node-gyp-native/4.0.0+gitAUTOINC+7245415296-r0 $ ll sysroot-destdir/OE/build/owpb/webos-ports/tmp-glibc/work/x86_64-linux/node-gyp-native/4.0.0+gitAUTOINC+7245415296-r0/recipe-sysroot-native/usr/lib/node_modules/
  total 8
  drwxr-xr-x 2 bitbake bitbake 4096 Sep 12 01:13 ./
  drwxr-xr-x 3 bitbake bitbake 4096 Sep 12 01:13 ../
  lrwxrwxrwx 2 bitbake bitbake   45 Sep 12 01:13 node-gyp -> ../../../../../../../../../../../../../../git/

  so this node_modules points back to ${S} alias ${WORKDIR}/git

* when some other components tries to use node-gyp-native and calls node-gyp, it fails:
  ERROR: nodejs-module-webos-dynaload-3.0.1-14+gitAUTOINC+4eedb88e6e-r0 do_configure: Function failed: do_configure (log file is located at /OE/build/owpb/webos-ports/tmp-glibc/work/aarch64-webos-linux/nodejs-module-webos-dynaload/3.0.1-14+gitAUTOINC+4eedb88e6e-r0/temp/log.do_configure.16359)
  ERROR: Logfile of failure stored in: /OE/build/owpb/webos-ports/tmp-glibc/work/aarch64-webos-linux/nodejs-module-webos-dynaload/3.0.1-14+gitAUTOINC+4eedb88e6e-r0/temp/log.do_configure.16359
  Log data follows:
  | DEBUG: Executing shell function do_configure
  | /OE/build/owpb/webos-ports/tmp-glibc/work/aarch64-webos-linux/nodejs-module-webos-dynaload/3.0.1-14+gitAUTOINC+4eedb88e6e-r0/temp/run.do_configure.16359: line 154: node-gyp: command not found
  | WARNING: /OE/build/owpb/webos-ports/tmp-glibc/work/aarch64-webos-linux/nodejs-module-webos-dynaload/3.0.1-14+gitAUTOINC+4eedb88e6e-r0/temp/run.do_configure.16359:1 exit 127 from 'node-gyp --arch aarch64 configure'
  | ERROR: Function failed: do_configure (log file is located at /OE/build/owpb/webos-ports/tmp-glibc/work/aarch64-webos-linux/nodejs-module-webos-dynaload/3.0.1-14+gitAUTOINC+4eedb88e6e-r0/temp/log.do_configure.16359)
  NOTE: recipe nodejs-module-webos-dynaload-3.0.1-14+gitAUTOINC+4eedb88e6e-r0: task do_configure: Failed
  ERROR: Task (/OE/build/owpb/webos-ports/meta-webos-ports/meta-luneos/recipes-webos/nodejs-module-webos/nodejs-module-webos-dynaload.bb:do_configure) failed with exit code '1'

  because in this case we're using node-gyp in nodejs-module-webos-dynaload RSS:
  OE raspberrypi3-64@luneos ~/webos/owpb/webos-ports $ ll /OE/build/owpb/webos-ports/tmp-glibc/work/aarch64-webos-linux/nodejs-module-webos-dynaload/3.0.1-14+gitAUTOINC+4eedb88e6e-r0/recipe-sysroot-native/usr/bin/node-gyp
  lrwxrwxrwx 1 bitbake bitbake 44 Sep 12 01:13 /OE/build/owpb/webos-ports/tmp-glibc/work/aarch64-webos-linux/nodejs-module-webos-dynaload/3.0.1-14+gitAUTOINC+4eedb88e6e-r0/recipe-sysroot-native/usr/bin/node-gyp -> ../lib/node_modules/node-gyp/bin/node-gyp.js

  but this time the node_modules/node-gyp points to non-existent git directory 14 levels up
  OE raspberrypi3-64@luneos ~/webos/owpb/webos-ports $ ll /OE/build/owpb/webos-ports/tmp-glibc/work/aarch64-webos-linux/nodejs-module-webos-dynaload/3.0.1-14+gitAUTOINC+4eedb88e6e-r0/recipe-sysroot-native/usr/lib/node_modules/
  total 12
  drwxr-xr-x  3 bitbake bitbake 4096 Sep 12 01:13 ./
  drwxr-xr-x  7 bitbake bitbake 4096 Sep 12 01:13 ../
  lrwxrwxrwx  1 bitbake bitbake   45 Sep 12 01:13 node-gyp -> ../../../../../../../../../../../../../../git
  drwxr-xr-x 11 bitbake bitbake 4096 Sep 12 01:13 npm/

  which in this case actually points to root of rootfs:
  /OE/build/owpb/webos-ports/tmp-glibc/work/aarch64-webos-linux/nodejs-module-webos-dynaload/3.0.1-14+gitAUTOINC+4eedb88e6e-r0/recipe-sysroot-native/usr/lib/node_modules/../../../../../../../../../../../../../../
  where we don't have "git" directory with node-gyp :)

* remove useless etc directory
* replace node-gyp symlink to ${S} with the content of ${S}

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>