README: add info about patches being welcome on github
* fixes yocto-check-layer test_readme:

INFO: test_readme (common.CommonCheckLayer.test_readme)
INFO:  ... FAIL
INFO: Traceback (most recent call last):
  File "/OE/build/oe-core/openembedded-core/scripts/lib/checklayer/cases/common.py", line 38, in test_readme
    self.assertIn('patch', data.lower())
AssertionError: 'patch' not found in "the open webos ports openembedded layer\nthis layer depends on:\n\nuri: git://github.com/openembedded/oe-core.git\nlayers: meta\nbranch: master\nrevision: head\n\nuri: git://github.com/openembedded/meta-oe.git\nlayers: meta-oe\nbranch: master\nrevision: head\n\nuri: git://github.com/meta-qt5/meta-qt5.git\nbranch: master\nrevision: head\n\nmain layer maintainers: simon busch <morphis@gravedo.de>, martin 'jama' jansa <martin.jansa@gmail.com>\n"

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>