vmwgfx-layout: CMakeLists.txt: use systemd_system_unitdir instead of /lib/systemd/system
* there isn't a better WEBOS_INSTALL_* variable for /lib/systemd/system
  but with usrmerge systemd_system_unitdir is /usr/lib/systemd/system
  not /lib/systemd/system:

  # $systemd_system_unitdir [2 operations]
  #   exported /OE/build/luneos-nanbield/openembedded-core/meta/conf/bitbake.conf:39
  #     [export] "1"
  #   set /OE/build/luneos-nanbield/openembedded-core/meta/conf/bitbake.conf:39
  #     "${nonarch_base_libdir}/systemd/system"
  # pre-expansion value:
  #   "${nonarch_base_libdir}/systemd/system"
  export systemd_system_unitdir="/usr/lib/systemd/system"

  and installing this to /lib/systemd/system causes do_package failure:
  ERROR: vmwgfx-layout-0.1+gitAUTOINC+8e43168d50-r0 do_package: Didn't find service unit 'vmwgfx-setlayout.service', specified in SYSTEMD_SERVICE:vmwgfx-layout.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>