webos_npm_env.bbclass: drop scripts-prepend-node-path
It isn't supported since npm-7 (removed with switch to @npmcli/config in:
https://github.com/npm/cli/commit/5dadeb83845a27f59cf4adfeb19bc8f07c3eec0f
later documentation removed it as well in:
https://github.com/npm/cli/commit/bc9c57dda7cf3abcdee17550205daf1a82e90438

npm-7 is used since nodejs-15, but until recent upgrade to nodejs-18 with npm-9
such unsupported option didn't cause fatal error, see:
https://github.com/nodejs/node/releases/tag/v18.14.0

"npm config set will no longer accept deprecated or invalid config options."

and other noteworthy changes in npm in:
https://github.com/npm/cli/releases/tag/v9.0.0

Introduced in meta-oe with:
https://git.openembedded.org/meta-openembedded/commit/?id=a4491a3e3ef0a73a3b3036808c1d244d43f925f0

ERROR: enact-dev-native-5.0.2-r12 do_compile: ExecutionError('/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/x86_64-linux/enact-dev-native/5.0.2-r12/temp/run.do_compile.2017993', 1, None, None)
ERROR: Logfile of failure stored in: /OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/x86_64-linux/enact-dev-native/5.0.2-r12/temp/log.do_compile.2017993
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: webos_npm_env: set HOME to WORKDIR
| NOTE: webos_npm_env: set npm cache
| npm WARN config dev Please use --include=dev instead.
| NOTE: webos_npm_env: clear npm cache and /OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/x86_64-linux/enact-dev-native/5.0.2-r12/git/node_modules
| npm WARN config dev Please use --include=dev instead.
| npm WARN using --force Recommended protections disabled.
| NOTE: webos_npm_env: config npm offline
| npm WARN config dev Please use --include=dev instead.
| NOTE: webos_npm_env: config npm package-lock
| npm WARN config dev Please use --include=dev instead.
| NOTE: webos_npm_env: config npm node-path
| npm WARN config dev Please use --include=dev instead.
| npm ERR! `scripts-prepend-node-path` is not a valid npm option

Other options should be updated as well as indicated by the warnings.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>