enact-dev-native, jsdoc-to-ts-native: npmsw: use destsuffix
see:
https://lists.openembedded.org/g/openembedded-architecture/message/2007
https://git.openembedded.org/bitbake/commit/?id=84f102954e10a3390fca9c26d5c3c639e952a2c9

Now the node_modules end in UNPACKDIR while npm.bbclass expects it in ${S}/node_modules.

Fixes:
Exception: FileNotFoundError: [Errno 2] No such file or directory: 'TOPDIR/BUILD/work/x86_64-linux/enact-dev-native/6.0.4/sources-unpack/git/node_modules/@aashutoshrathi/word-wrap/package.json'

It would be even better for npmsw:// to fetch the npm-shrinkwrap.json
file from anywhere in FILESPATH (like file:// does), this currently
fails, because it calls open() on the npmsw:// directly so it needs
full path to file in metadata

WARNING: recipes-upstreamable/nodejs-module/nodejs-module-usocket_1.0.1.bb: Exception during build_dependencies for fetcher_hashes_dummyfunc                          | ETA:  --:--:--
WARNING: recipes-upstreamable/nodejs-module/nodejs-module-usocket_1.0.1.bb: Error during finalise of recipes-upstreamable/nodejs-module/nodejs-module-usocket_1.0.1.bb
ERROR: ExpansionError during parsing recipes-upstreamable/nodejs-module/nodejs-module-usocket_1.0.1.bb
Traceback (most recent call last):
  File "bitbake/lib/bb/fetch2/__init__.py", line 834, in get_hashvalue(d=<bb.data_smart.DataSmart object at 0x7fea49f45160>, method_name='sortable_revision'):
     def get_hashvalue(d, method_name='sortable_revision'):
    >    pkgv, revs = _get_srcrev(d, method_name=method_name)
         return " ".join(revs)
  File "bitbake/lib/bb/fetch2/__init__.py", line 778, in _get_srcrev(d=<bb.data_smart.DataSmart object at 0x7fea49f45160>, method_name='sortable_revision'):
         revs = []
    >    fetcher = Fetch(d.getVar('SRC_URI').split(), d)
         urldata = fetcher.ud
  File "bitbake/lib/bb/fetch2/__init__.py", line 1794, in Fetch.__init__(urls=['npm://registry.npmjs.org/;package=usocket;version=1.0.1', 'npmsw://npm-shrinkwrap.json;destsuffix=npm', 'file://0001-package.json-use-node-gyp-10.patch'], d=<bb.data_smart.DataSmart object at 0x7fea49f45160>, cache=True, localonly=False, connection_cache=None):
                     try:
    >                    self.ud[url] = FetchData(url, d, localonly)
                         self.ud[url].unpack_tracer = unpack_tracer
  File "bitbake/lib/bb/fetch2/__init__.py", line 1346, in FetchData.__init__(url='npmsw://npm-shrinkwrap.json;destsuffix=npm', d=<bb.data_smart.DataSmart object at 0x7fea49f45160>, localonly=False):
             if hasattr(self.method, "urldata_init"):
    >            self.method.urldata_init(self, d)

  File "bitbake/lib/bb/fetch2/npmsw.py", line 218, in NpmShrinkWrap.urldata_init(ud=<bb.fetch2.FetchData object at 0x7fea49f5fad0>, d=<bb.data_smart.DataSmart object at 0x7fea49f45160>):
             except Exception as e:
    >            raise ParameterError("Invalid shrinkwrap file: %s" % str(e), ud.url)

bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue], expression was ${@bb.fetch.get_hashvalue(d)} which triggered exception ParameterError: URL: 'npmsw://npm-shrinkwrap.json;destsuffix=npm' has invalid parameters. Invalid shrinkwrap file: [Errno 2] No such file or directory: 'npm-shrinkwrap.json'
The variable dependency chain for the failure is: fetcher_hashes_dummyfunc[vardepvalue]

ERROR: Parsing halted due to errors, see error messages above

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>