db8: Fix build with leveldb-1.23
* explicitly disable rtti like leveldb does since:
  https://github.com/google/leveldb/commit/69061b464ab1da287da9b7ffec1ed911b754403b
  to fix:

FAILED: src/db-luna/mojodb-luna
: && /OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++ --sysroot=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2  --sysroot=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map  -fmacro-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/git=/usr/src/debug/db8/3.2.0-28+git-r40  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/git=/usr/src/debug/db8/3.2.0-28+git-r40  -fmacro-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/build=/usr/src/debug/db8/3.2.0-28+git-r40  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/build=/usr/src/debug/db8/3.2.0-28+git-r40  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot=  -fmacro-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot=  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot-native=  -fvisibility-inlines-hidden -pthread -DUSE_PMLOG -DWITH_SNAPPY_COMPRESSION -Wall -Wextra -fPIC -Wconversion -std=c++14 -Wno-unused-but-set-variable -Wno-unused-variable -fno-exceptions -frename-registers -DMOJ_LINUX -fno-strict-aliasing -Wno-psabi -DMOJ_INTERNAL -D_REENTRANT -Werror=return-type -Wno-unused-parameter -Wno-empty-body -Wl,--no-undefined -DWITH_SEARCH_QUERY_CACHE -DUSE_PMLOG_DECLARATION  -DMOJ_USE_LDB -DMOJ_USE_SANDWICH -DNDEBUG  -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2  --sysroot=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map  -fmacro-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/git=/usr/src/debug/db8/3.2.0-28+git-r40  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/git=/usr/src/debug/db8/3.2.0-28+git-r40  -fmacro-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/build=/usr/src/debug/db8/3.2.0-28+git-r40  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/build=/usr/src/debug/db8/3.2.0-28+git-r40  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot=  -fmacro-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot=  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot-native=  -fvisibility-inlines-hidden -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fcanon-prefix-map  -fmacro-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/git=/usr/src/debug/db8/3.2.0-28+git-r40  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/git=/usr/src/debug/db8/3.2.0-28+git-r40  -fmacro-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/build=/usr/src/debug/db8/3.2.0-28+git-r40  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/build=/usr/src/debug/db8/3.2.0-28+git-r40  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot=  -fmacro-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot=  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot-native=  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fcanon-prefix-map  -fmacro-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/git=/usr/src/debug/db8/3.2.0-28+git-r40  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/git=/usr/src/debug/db8/3.2.0-28+git-r40  -fmacro-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/build=/usr/src/debug/db8/3.2.0-28+git-r40  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/build=/usr/src/debug/db8/3.2.0-28+git-r40  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot=  -fmacro-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot=  -fdebug-prefix-map=/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot-native=   -rdynamic src/db-luna/CMakeFiles/mojodb-luna.dir/MojDbLunaServiceApp.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/MojDbLunaServiceDb.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/leveldb/defs.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/leveldb/MojDbLevelEngine.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/leveldb/MojDbLevelFactory.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/leveldb/MojDbLevelDatabase.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/leveldb/MojDbLevelQuery.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/leveldb/MojDbLevelTxn.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/leveldb/MojDbLevelSeq.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/leveldb/MojDbLevelCursor.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/leveldb/MojDbLevelEnv.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/leveldb/MojDbLevelIndex.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/leveldb/MojDbLevelItem.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/leveldb/MojDbLevelTxnIterator.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/leveldb/MojDbLevelIterator.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/leveldb/MojDbLevelContainerIterator.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichEngine.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichFactory.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichDatabase.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichQuery.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichTxn.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichSeq.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichEnv.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichIndex.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichItem.cpp.o src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichLazyUpdater.cpp.o -o src/db-luna/mojodb-luna  -L/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot/usr/lib  -lglib-2.0  -L/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot/usr/lib  -lgthread-2.0  -pthread  -lglib-2.0  src/db/libmojodb.so.3.2.0  src/luna/libmojoluna.so.3.2.0  -latomic  -lleveldb  -lleveldb  -L/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot/usr/lib  -lluna-service2  -licuuc  -licui18n  src/core/libmojocore.so.3.2.0  -L/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot/usr/lib  -lglib-2.0  -lgthread-2.0  -lglib-2.0  -lgthread-2.0  -pthread  -lPmLogLib  /OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot/usr/lib/libboost_regex.so.1.83.0 && :
/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot-native/usr/bin/x86_64-webos-linux/../../libexec/x86_64-webos-linux/gcc/x86_64-webos-linux/13.2.0/ld: src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichEngine.cpp.o:(.data.rel.ro._ZTIN7leveldb10AsIteratorINS_10SandwichDBINS_5TxnDBINS_8BottomDBEEEtE4Part6WalkerEEE[_ZTIN7leveldb10AsIteratorINS_10SandwichDBINS_5TxnDBINS_8BottomDBEEEtE4Part6WalkerEEE]+0x10): undefined reference to `typeinfo for leveldb::Iterator'
/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot-native/usr/bin/x86_64-webos-linux/../../libexec/x86_64-webos-linux/gcc/x86_64-webos-linux/13.2.0/ld: src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichEngine.cpp.o:(.data.rel.ro._ZTIN7leveldb10AsIteratorINS_5TxnDBINS_8BottomDBEE6WalkerEEE[_ZTIN7leveldb10AsIteratorINS_5TxnDBINS_8BottomDBEE6WalkerEEE]+0x10): undefined reference to `typeinfo for leveldb::Iterator'
/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot-native/usr/bin/x86_64-webos-linux/../../libexec/x86_64-webos-linux/gcc/x86_64-webos-linux/13.2.0/ld: src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichEngine.cpp.o:(.data.rel.ro._ZTIN7leveldb10AsIteratorINS_10SandwichDBINS_8BottomDBEtE4Part6WalkerEEE[_ZTIN7leveldb10AsIteratorINS_10SandwichDBINS_8BottomDBEtE4Part6WalkerEEE]+0x10): undefined reference to `typeinfo for leveldb::Iterator'
/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot-native/usr/bin/x86_64-webos-linux/../../libexec/x86_64-webos-linux/gcc/x86_64-webos-linux/13.2.0/ld: src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichEngine.cpp.o:(.data.rel.ro._ZTIN7leveldb10AsIteratorINS_8MemoryDB6WalkerEEE[_ZTIN7leveldb10AsIteratorINS_8MemoryDB6WalkerEEE]+0x10): undefined reference to `typeinfo for leveldb::Iterator'
/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/db8/3.2.0-28+git/recipe-sysroot-native/usr/bin/x86_64-webos-linux/../../libexec/x86_64-webos-linux/gcc/x86_64-webos-linux/13.2.0/ld: src/db-luna/CMakeFiles/mojodb-luna.dir/__/engine/sandwich/MojDbSandwichQuery.cpp.o:(.data.rel.ro._ZTIN7leveldb10AsIteratorINS_5CoverI18PtrIteratorFactoryNS_10SandwichDBINS_5TxnDBINS_8BottomDBEEEtE4PartEE6WalkerEEE[_ZTIN7leveldb10AsIteratorINS_5CoverI18PtrIteratorFactoryNS_10SandwichDBINS_5TxnDBINS_8BottomDBEEEtE4PartEE6WalkerEEE]+0x10): undefined reference to `typeinfo for leveldb::Iterator'
collect2: error: ld returned 1 exit status

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>