org.webosports.app.settings-qml: fix SRCREV and switch back to qml-based branch
* fixes:
  ERROR: org.webosports.app.settings-qml-0.4.0-1+gitAUTOINC+87edcf2d8c-r0 do_fetch: Fetcher failure: Unable to find revision 87edcf2d8cc8417c28741ceb93427067586f2826 in branch herrie/qt6 even from upstream

* https://github.com/webOS-ports/org.webosports.app.settings/pull/111
  was merged into qml-based branch

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>