umediaserver: python: fix build with python-3.13
python-native was upgraded to 3.13 in:
https://git.openembedded.org/openembedded-core/commit/?id=0b49c9aa31279ecda565cc66b63d1d61723b37b8
now umediaserver is failing to build.

See https://docs.python.org/3/whatsnew/3.13.html
Remove the PyEval_ThreadsInitialized() function, deprecated in Python
3.9. Since Python 3.7, Py_Initialize() always creates the GIL: calling
PyEval_InitThreads() does nothing and PyEval_ThreadsInitialized() always
returns non-zero. (Contributed by Victor Stinner in gh-105182.)

Fixes:

TOPDIR/BUILD/work/qemux86_64-webos-linux/umediaserver/1.0.0-gav.50/build/test/python/binding/CMakeFiles/_uMediaClient.dir/uMediaClientPYTHON_wrap.cxx: In constructor 'uMediaServer::MediaPlayer::MediaPlayer()':
TOPDIR/BUILD/work/qemux86_64-webos-linux/umediaserver/1.0.0-gav.50/build/test/python/binding/CMakeFiles/_uMediaClient.dir/uMediaClientPYTHON_wrap.cxx:3369:22: error: 'PyEval_ThreadsInitialized' was not declared in this scope
 3369 |                 if (!PyEval_ThreadsInitialized())
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~
TOPDIR/BUILD/work/qemux86_64-webos-linux/umediaserver/1.0.0-gav.50/build/test/python/binding/CMakeFiles/_uMediaClient.dir/uMediaClientPYTHON_wrap.cxx:3370:43: warning: 'void PyEval_InitThreads()' is deprecated [-Wdeprecated-declarations]
 3370 |                         PyEval_InitThreads();
      |                         ~~~~~~~~~~~~~~~~~~^~