node-gyp-packages-native: use UNPACKDIR
ERROR: QA Issue: node-gyp-packages-native: LIC_FILES_CHKSUM points to an invalid file:
TOPDIR/BUILD/work/x86_64-linux/node-gyp-packages-native/0.12.2/node-gyp-packages/abbrev_1.0.5/package/LICENSE [license-checksum]

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
(cherry picked from commit 6f694c8291e56ff6d57a6d444ea2ccdcc05c5906)