pulseaudio-modules-droid-hidl: fix dependencies
* there is no recipe for pulseaudio-module-dbus-protocol but it's a package
  created by pulseaudio:
  $ find tmp-glibc/work/core2-64-webos-linux/pulseaudio/16.0-r0/packages-split/pulseaudio-module-dbus-protocol
tmp-glibc/work/core2-64-webos-linux/pulseaudio/16.0-r0/packages-split/pulseaudio-module-dbus-protocol
tmp-glibc/work/core2-64-webos-linux/pulseaudio/16.0-r0/packages-split/pulseaudio-module-dbus-protocol/usr
tmp-glibc/work/core2-64-webos-linux/pulseaudio/16.0-r0/packages-split/pulseaudio-module-dbus-protocol/usr/lib
tmp-glibc/work/core2-64-webos-linux/pulseaudio/16.0-r0/packages-split/pulseaudio-module-dbus-protocol/usr/lib/pulseaudio
tmp-glibc/work/core2-64-webos-linux/pulseaudio/16.0-r0/packages-split/pulseaudio-module-dbus-protocol/usr/lib/pulseaudio/modules
tmp-glibc/work/core2-64-webos-linux/pulseaudio/16.0-r0/packages-split/pulseaudio-module-dbus-protocol/usr/lib/pulseaudio/modules/module-dbus-protocol.so

* it was added in:
  https://github.com/webOS-ports/meta-webos-ports/commit/e5e38c9cf7d12045659d7739d2fb3626bbd38c38
  but probably never built successfully

* move it from DEPENDS to RDEPENDS: to fix:
  ERROR: Nothing PROVIDES 'pulseaudio-module-dbus-protocol' (but /OE/build/luneos-langdale/webos-ports/meta-webos-ports/meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-modules-droid-hidl_git.bb DEPENDS on or otherwise requires it). Close matches:
  pulseaudio RPROVIDES pulseaudio-module-dbus-protocol
  pulseaudio-modules-droid
  pulseaudio-modules-droid-hidl
  ERROR: Required build target 'pulseaudio-modules-droid-hidl' has no buildable providers.
  Missing or unbuildable dependency chain was: ['pulseaudio-modules-droid-hidl', 'pulseaudio-module-dbus-protocol']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>