luna-surfacemanager: update the patch based on /usr/include/QtGui/qopengl.h from qtbase-6
* fixes:
arm-webos-linux-gnueabi-g++  -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a8 --sysroot=/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot -c -include .pch/WebOSCoreCompositor -pipe -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0=/usr/src/debug/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0                      -fdebug-prefix-map=/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0=/usr/src/debug/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0                      -fdebug-prefix-map=/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot=                      -fdebug-prefix-map=/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden -g -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -Wsuggest-override -D_REENTRANT -fPIC -DWEBOS_INSTALL_QML=\"/usr/lib/qml\" -DWEBOS_INSTALL_QTPLUGINSDIR=\"/usr/plugins\" -DUSE_PMLOGLIB -DQT_WAYLAND_COMPOSITOR_QUICK -DWEBOS_INSTALL_QML=\"/usr/lib/qml\" -DUPSTART_SIGNALING -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_WEBOSCOMPOSITOR_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_WEBOSCOMPOSITOREXTENSION_LIB -DQT_WAYLANDCOMPOSITOR_LIB -DQT_WAYLANDCOMPOSITOR_LIB -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QMLINTEGRATION_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_WAYLANDGLOBAL_LIB -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/git/modules/weboscompositor -I. -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/git/modules/weboscompositor/shell -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/git/modules/weboscompositor -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/git/modules/weboscompositor/input -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/git/modules/weboscompositor/surfacegroup -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/git/modules/weboscompositor/webosseat -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/git/modules/weboscompositor -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webs-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/git/modules/weboscompositor/foreign -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/git/modules/weboscompositor -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/git/modules/weboscompositor/webostablet -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/git/modules/weboscompositor -I../../include -I../../include/WebOSCoreCompositor -I../../include/WebOSCoreCompositor/0.0.1 -I../../include/WebOSCoreCompositor/0.0.1/WebOSCoreCompositor -I../../include/WebOSCoreCompositorExtension -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtWaylandCompositor/6.3.0 -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtWaylandCompositor/6.3.0/QtWaylandCompositor -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtWaylandCompositor -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtQuick/6.3.0 -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtQuick/6.3.0/QtQuick -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtQuick -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtOpenGL -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtGui/6.3.0 -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtGui/6.3.0/QtGui -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtGui -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtQmlModels/6.3.0 -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtQmlModels/6.3.0/QtQmlModels -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtQmlModels -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtQml/6.3.0 -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtQml/6.3.0/QtQml -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtQml -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtQmlIntegration -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtNetwork -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtCore/6.3.0 -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtCore/6.3.0/QtCore -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtCore -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtWaylandGlobal -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtWaylandGlobal/6.3.0 -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtWaylandGlobal/6.3.0/QtWaylandGlobal -I.moc -I/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/lib/mkspecs/linux-oe-g++ -o .obj/webosscreenshot.o /mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/git/modules/weboscompositor/webosscreenshot.cpp
In file included from /mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/git/modules/weboscompositor/webosscreenshot.cpp:32:
/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/GLES2/gl2.h:572:37: error: conflicting declaration of C function 'void glShaderSource(GLuint, GLsizei, const GLchar**, const GLint*)'
  572 | GL_APICALL void         GL_APIENTRY glShaderSource (GLuint shader, GLsizei count, const GLchar** string, const GLint* length);
      |                                     ^~~~~~~~~~~~~~
In file included from /mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtGui/qopengl.h:105,
                 from /mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/QtGui/QtGui:60,
                 from ../../include/WebOSCoreCompositor/WebOSCoreCompositorDepends:4:
/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/luna-surfacemanager/2.0.0-372+gitAUTOINC+dfbf316e3d-r0/recipe-sysroot/usr/include/GLES3/gl32.h:621:29: note: previous declaration 'void glShaderSource(GLuint, GLsizei, const GLchar* const*, const GLint*)'
  621 | GL_APICALL void GL_APIENTRY glShaderSource (GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length);
      |                             ^~~~~~~~~~~~~~

again now when QtGui/qopengl.h was changed to use QT_CONFIG instead of QT_OPENGL_ES_3_2 defines.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>