enact-dev: use UNPACKDIR directly
https://git.openembedded.org/openembedded-core/commit/?h=master-next&id=0f32d28545a963fe0bf8bfc53d27b5ab0cedd707

deletes workdir + '/' + basedir with bb.utils.remove
then calls fetcher.unpack(d.getVar('UNPACKDIR'))
and moves unpackdir + '/' + basedir to it with shutil.move

but npmsw fetcher creates ${S} as workdir + '/' + basedir in:
https://git.openembedded.org/bitbake/tree/lib/bb/fetch2/npmsw.py#n277
which causes the shutil.move to move it as subdirectory like
${WORKDIR}/git/git e.g. jsdoc-to-ts-native/1.0.0/git/git/README.md

https://git.openembedded.org/bitbake/commit/?id=84f102954e10a3390fca9c26d5c3c639e952a2c9
fixed this issue for jsdoc-to-ts-native but enact-dev-native
is still unhappy about the paths being changed from ${WORKDIR}/sources-unpacked
to ${WORKDIR}/git.

Exception: FileNotFoundError: [Errno 2] No such file or directory:
'TOPDIR/BUILD/work/x86_64-linux/enact-dev-native/6.0.4/sources-unpack/git/node_modules/@aashutoshrathi/word-wrap/package.json'
the file exists, but not under 'git' as:
'TOPDIR/BUILD/work/x86_64-linux/enact-dev-native/6.0.4/sources-unpack/node_modules/@aashutoshrathi/word-wrap/package.json'

meta-luneos/recipes-webos-ose/enact-dev/enact-dev/npm-shrinkwrap.json:    "node_modules/@aashutoshrathi/word-wrap": {
meta-luneos/recipes-webos-ose/enact-dev/enact-dev/npm-shrinkwrap.json:    "node_modules/@enact/dev-utils/node_modules/@aashutoshrathi/word-wrap": {
meta-luneos/recipes-webos-ose/enact-dev/enact-dev/npm-shrinkwrap.json:    "node_modules/@enact/dev-utils/node_modules/eslint-config-enact/node_modules/@aashutoshrathi/word-wrap": {
meta-luneos/recipes-webos-ose/enact-dev/enact-dev/npm-shrinkwrap.json:    "node_modules/@enact/dev-utils/node_modules/eslint-config-enact/node_modules/babel-preset-enact/node_modules/@aashutoshrathi/word-wrap": {
meta-luneos/recipes-webos-ose/enact-dev/enact-dev/npm-shrinkwrap.json:    "node_modules/@enact/dev-utils/node_modules/eslint-config-enact/node_modules/eslint-plugin-enact/node_modules/@aashutoshrathi/word-wrap": {
meta-luneos/recipes-webos-ose/enact-dev/enact-dev/npm-shrinkwrap.json:    "node_modules/@enact/dev-utils/node_modules/eslint-plugin-enact/node_modules/@aashutoshrathi/word-wrap": {
meta-luneos/recipes-webos-ose/enact-dev/enact-dev/npm-shrinkwrap.json:    "node_modules/babel-preset-enact/node_modules/@aashutoshrathi/word-wrap": {
meta-luneos/recipes-webos-ose/enact-dev/enact-dev/npm-shrinkwrap.json:    "node_modules/eslint-config-enact/node_modules/@aashutoshrathi/word-wrap": {
meta-luneos/recipes-webos-ose/enact-dev/enact-dev/npm-shrinkwrap.json:    "node_modules/eslint-config-enact/node_modules/babel-preset-enact/node_modules/@aashutoshrathi/word-wrap": {
meta-luneos/recipes-webos-ose/enact-dev/enact-dev/npm-shrinkwrap.json:    "node_modules/eslint-config-enact/node_modules/eslint-plugin-enact/node_modules/@aashutoshrathi/word-wrap": {
meta-luneos/recipes-webos-ose/enact-dev/enact-dev/npm-shrinkwrap.json:    "node_modules/eslint-plugin-enact/node_modules/@aashutoshrathi/word-wrap": {

ERROR: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:npm_do_configure(d)
     0003:
File: 'TOPDIR/oe-core/meta/classes-recipe/npm.bbclass', lineno: 203, function: npm_do_configure
     0199:    dev = bb.utils.to_boolean(d.getVar("NPM_INSTALL_DEV"), False)
     0200:
     0201:    if has_shrinkwrap_file:
     0202:        foreach_dependencies(orig_shrinkwrap, _count_dependency, dev)
 *** 0203:        foreach_dependencies(orig_shrinkwrap, _cache_dependency, dev)
     0204:
     0205:    # Manage Peer Dependencies
     0206:    if has_shrinkwrap_file:
     0207:        packages = orig_shrinkwrap.get("packages", {})
File: 'TOPDIR/bitbake/lib/bb/fetch2/npmsw.py', lineno: 69, function: foreach_dependencies
     0065:                name = package.split('node_modules/')[-1]
     0066:                package_infos = packages.get(package, {})
     0067:                if dev == False and package_infos.get("dev", False):
     0068:                    continue
 *** 0069:                callback(name, package_infos, package)
     0070:    else:
     0071:        _walk_deps(shrinkwrap.get("dependencies", {}), [])
     0072:
     0073:class NpmShrinkWrap(FetchMethod):
File: 'TOPDIR/oe-core/meta/classes-recipe/npm.bbclass', lineno: 176, function: _cache_dependency
     0172:    def _cache_dependency(name, params, destsuffix):
     0173:        with tempfile.TemporaryDirectory() as tmpdir:
     0174:            # Add the dependency to the npm cache
     0175:            destdir = os.path.join(d.getVar("S"), destsuffix)
 *** 0176:            (tarball, pkg) = npm_pack(env, destdir, tmpdir)
     0177:            _npm_cache_add(tarball, pkg)
     0178:            # Add its signature to the cached shrinkwrap
     0179:            dep = params
     0180:            dep["version"] = pkg['version']
File: 'TOPDIR/oe-core/meta/classes-recipe/npm.bbclass', lineno: 71, function: npm_pack
     0067:    import os
     0068:    import json
     0069:
     0070:    src = os.path.join(srcdir, 'package.json')
 *** 0071:    with open(src) as f:
     0072:        j = json.load(f)
     0073:
     0074:    # base does not really matter and is for documentation purposes
     0075:    # only.  But the 'version' part must exist because other parts of
Exception: FileNotFoundError: [Errno 2] No such file or directory: 'TOPDIR/BUILD/work/x86_64-linux/enact-dev-native/6.0.4/sources-unpack/git/node_modules/@aashutoshrathi/word-wrap/package.json'

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>