busybox-static: rename to match the recipe in oe-core
* fixes:
  ERROR: ParseError at /home/jenkins/workspace/luneos-unstable/webos-ports/meta-webos-ports/meta-luneos/recipes-core/busybox/busybox-static_1.31.0.bb:3: Could not include required file recipes-core/busybox/busybox_1.31.0.bb

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>