ofono: fix QA issue
* fixes:
  ERROR: ofono-1.19+gitrAUTOINC+ca1d06c37a-r0 do_package_qa: QA Issue:
  /usr/lib/ofono/test/test-ss-control-cb contained in package
  ofono-tests requires /usr/bin/python, but no providers found in
  RDEPENDS_ofono-tests? [file-rdeps]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>