webos-initscripts: don't install initctl twice and respect WEBOS_INSTALL_SBINDIR
* initctl was once installed in /usr/bin/initctl by webos_build_program
  and then again to /sbin/initctl by:
  install(TARGETS  DESTINATION /sbin)

* all utils were installed to /sbin even when sbindir is set to /usr/sbin
  with usrmerge in DISTRO_FEATURES, causing installed-vs-shipped QA:

ERROR: webos-initscripts-1.0-r0 do_package: QA Issue: webos-initscripts: Files/directories were installed but not shipped in any package:
  /sbin/restart
  /sbin/start
  /sbin/status
  /sbin/initctl
  /sbin/stop
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
webos-initscripts: 5 installed and not shipped files. [installed-vs-shipped]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>