Revert "webos: Apply npmsw to SRC_URI"
This reverts commit d5ef0173ceb9c607840be6f5fa80628b9d1f041f.

Causes git/node_modules/@babel/runtime to be missing in many recipes
http://gecko.lge.com:8000/Builds/Details/2980073

All fail the same with:
ERROR: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:npm_do_configure(d)
     0003:
File: 'TOPDIR/oe-core/meta/classes-recipe/npm.bbclass', lineno: 205, function: npm_do_configure
     0201:    dev = bb.utils.to_boolean(d.getVar("NPM_INSTALL_DEV"), False)
     0202:
     0203:    if has_shrinkwrap_file:
     0204:        foreach_dependencies(orig_shrinkwrap, _count_dependency, dev)
 *** 0205:        foreach_dependencies(orig_shrinkwrap, _cache_dependency, dev)
     0206:
     0207:    # Manage Peer Dependencies
     0208:    if has_shrinkwrap_file:
     0209:        packages = orig_shrinkwrap.get("packages", {})
File: 'TOPDIR/bitbake/lib/bb/fetch2/npmsw.py', lineno: 59, function: foreach_dependencies
     0055:            continue
     0056:        elif data.get("inBundle", False):
     0057:            continue
     0058:        name = location.split('node_modules/')[-1]
 *** 0059:        callback(name, data, location)
     0060:
     0061:class NpmShrinkWrap(FetchMethod):
     0062:    """Class to fetch all package from a shrinkwrap file"""
     0063:
File: 'TOPDIR/oe-core/meta/classes-recipe/npm.bbclass', lineno: 178, function: _cache_dependency
     0174:    def _cache_dependency(name, params, destsuffix):
     0175:        with tempfile.TemporaryDirectory() as tmpdir:
     0176:            # Add the dependency to the npm cache
     0177:            destdir = os.path.join(d.getVar("S"), destsuffix)
 *** 0178:            (tarball, pkg) = npm_pack(env, destdir, tmpdir)
     0179:            _npm_cache_add(tarball, pkg)
     0180:            # Add its signature to the cached shrinkwrap
     0181:            dep = params
     0182:            dep["version"] = pkg['version']
File: 'TOPDIR/oe-core/meta/classes-recipe/npm.bbclass', lineno: 71, function: npm_pack
     0067:    import os
     0068:    import json
     0069:
     0070:    src = os.path.join(srcdir, 'package.json')
 *** 0071:    with open(src) as f:
     0072:        j = json.load(f)
     0073:
     0074:    # base does not really matter and is for documentation purposes
     0075:    # only. But the 'version' part must exist because other parts of
Exception: FileNotFoundError: [Errno 2] No such file or directory: 'TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.app.home/0.1.0-41/git/node_modules/@babel/runtime/package.json'

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>