luneos.inc: use new oe.buildcfg module
* old functions were removed in:
  https://git.openembedded.org/openembedded-core/commit/?id=439cdf8a1e52fd2c4dc81dc40ce7e6af282ce7ac

* fixes:
WARNING: /OE/build/luneos-langdale/webos-ports/meta-webos-ports/meta-luneos/recipes-webos/chromium/webruntime_91.bb: Exception during build_dependencies for do_exportbuildscript                                             | ETA:  --:--:--
ERROR: ExpansionError during parsing /OE/build/luneos-langdale/webos-ports/meta-webos-ports/meta-luneos/recipes-webos/chromium/webruntime_91.bb
Traceback (most recent call last):
  File "Var <WEBOS_DISTRO_TOPDIR_REVISION>", line 1, in <module>
bb.data_smart.ExpansionError: Failure expanding variable WEBOS_DISTRO_TOPDIR_REVISION, expression was ${@base_get_metadata_git_revision('/OE/build/luneos-langdale/webos-ports/../common/', None).strip()} which triggered exception NameError: name 'base_get_metadata_git_revision' is not defined
The variable dependency chain for the failure is: WEBOS_DISTRO_TOPDIR_REVISION -> do_exportbuildscript

ERROR: Parsing halted due to errors, see error messages above

Summary: There was 1 WARNING message.
Summary: There were 2 ERROR messages, returning a non-zero exit code.

WARNING: /OE/build/luneos-langdale/webos-ports/openembedded-core/meta/recipes-extended/lsb/lsb-release_1.4.bb: Exception during build_dependencies for do_install                                                             | ETA:  --:--:--
ERROR: ExpansionError during parsing /OE/build/luneos-langdale/webos-ports/openembedded-core/meta/recipes-extended/lsb/lsb-release_1.4.bb
Traceback (most recent call last):
  File "Var <WEBOS_DISTRO_TOPDIR_BRANCH>", line 1, in <module>
bb.data_smart.ExpansionError: Failure expanding variable WEBOS_DISTRO_TOPDIR_BRANCH, expression was ${@base_get_metadata_git_branch('/OE/build/luneos-langdale/webos-ports/../common/', None).strip()} which triggered exception NameError: name 'base_get_metadata_git_branch' is not defined
The variable dependency chain for the failure is: WEBOS_DISTRO_TOPDIR_BRANCH -> BUILD_TREE -> do_install

ERROR: Parsing halted due to errors, see error messages above

Summary: There was 1 WARNING message.
Summary: There were 2 ERROR messages, returning a non-zero exit code.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>