anbox: add COMPATIBLE_MACHINE restriction
* fixes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'anbox-data' (but /OE/build/luneos-master/webos-ports/meta-webos-ports/meta-luneos/recipes-support/anbox/anbox.bb RDEPENDS on or otherwise requires it)
anbox-data was skipped: incompatible with machine qemux86 (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'anbox-data' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['anbox-data']
ERROR: Nothing RPROVIDES 'anbox-dev' (but /OE/build/luneos-master/webos-ports/meta-webos-ports/meta-luneos/recipes-support/anbox/anbox.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'anbox-dev'
NOTE: Runtime target 'anbox-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['anbox-dev']
ERROR: Nothing RPROVIDES 'anbox' (but /OE/build/luneos-master/webos-ports/meta-webos-ports/meta-luneos/recipes-support/anbox/anbox.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'anbox'
NOTE: Runtime target 'anbox' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['anbox']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>