webos-nettools: use gnu17 even with gcc-15
gcc-15 uses gnu23 standard for c since:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212
but this component isn't readly for it and fails to build.

webos-nettools/1.1.0-43/git/src/main.c:51:13: error: too many arguments to function 'initialize_nettools_ls2_calls'; expected 0, have 1

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>