bluebinder: restrict COMPATIBLE_MACHINE to halium
fixes:

http://jenkins.nas-admin.org/job/LuneOS/view/testing/job/luneos-testing_workspace-compare-signatures/219/console

ERROR: Nothing RPROVIDES 'android-property-service' (but /home/jenkins/workspace/luneos-testing/webos-ports/meta-webos-ports/meta-luneos/recipes-support/bluebinder/bluebinder.bb RDEPENDS on or otherwise requires it)
android-property-service was skipped: incompatible with machine qemux86 (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'android-property-service' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['android-property-service']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'bluebinder', 'android-property-service']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>