notificationmgr: Drop libxml requirement
Seems that libxml++ 2.6 is no longer available after recent meta-oe removal https://github.com/openembedded/meta-openembedded/commit/04eefd302d58c403e011ad34d1d346703a364a53. Simple replacement with libxml++-5 doesn't work without a lot of changes.

Going through the code seems it's only used by parseDoc function which isn't called anywhere.

Let's simply drop this piece of code instead.

Fixes:

We got this failure:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'libxml++-5' (but
/media/herrie/LuneOS/scarthgap/webos-ports/meta-webos-ports/meta-luneos/recipes-webos-ose/notificationmgr/notificationmgr.bb
DEPENDS on or otherwise requires it). Close matches:
  libxml++-5.0
    libxml2
      libxmlb

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>