qttools: disable clang support even when meta-clang is included
Fails with clang-19

Avoids
qttools-native/6.7.2/git/src/linguist/lupdate/clangtoolastreader.cpp:785:73: error: <C3><A2><C2><80><C2><98>const class clang::FileEntry has no member named getName

FileEntry::GetName() was deprecated since clang-17 and removed in clang-19 with:
https://github.com/llvm/llvm-project/commit/6c1dbd5359c4336d03b11faeaea8459b421f2c5c

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>