sdl2-opengles-test: build only gles2 version for rpi
* raspberrpi3 doesn't provide glesv1_cm and build for sdl2_opengles1_test
  fails with:
in file included from main_glesv1.cpp:31:0:
common.h:32:10: fatal error: SDL.h: No such file or directory
 #include <SDL.h>
          ^~~~~~~

  because when the pkg-config call in makefile doesn't find glesv1_cm
  it doesn't print the flags also for sdl2 which is checked in the
  same call, if I separate this into multiple pkg-config calls, then
  only the first one fails, but there are still missing symbols from
  glesv1_cm so it doesn't help:

NOTE: make -j 9 TARGETS=sdl2_opengles1_test sdl2_opengles2_test
Package glesv1_cm was not found in the pkg-config search path.
Perhaps you should add the directory containing `glesv1_cm.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glesv1_cm' found
arm-webos-linux-gnueabi-g++  -march=armv7ve -marm -mfpu=neon-vfpv4  -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/OE/build/owpb/webos-ports/tmp-glibc/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/OE/build/owpb/webos-ports/tmp-glibc/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0=/usr/src/debug/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0 -fdebug-prefix-map=/OE/build/owpb/webos-ports/tmp-glibc/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/recipe-sysroot-native= -fdebug-prefix-map=/OE/build/owpb/webos-ports/tmp-glibc/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/recipe-sysroot=  -fvisibility-inlines-hidden -DDATADIR=\"/usr/share/sdl2-opengles-test/\" -o sdl2_opengles1_test main_glesv1.cpp common.cpp -D_REENTRANT -I/OE/build/owpb/webos-ports/tmp-glibc/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/recipe-sysroot/usr/include/SDL2 -lSDL2
/usr/src/debug/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/git/main_glesv1.cpp:50: error: undefined reference to 'glClearColor'
/usr/src/debug/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/git/main_glesv1.cpp:56: error: undefined reference to 'glMatrixMode'
/usr/src/debug/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/git/main_glesv1.cpp:57: error: undefined reference to 'glLoadIdentity'
/usr/src/debug/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/git/main_glesv1.cpp:58: error: undefined reference to 'glOrthof'
/usr/src/debug/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/git/main_glesv1.cpp:80: error: undefined reference to 'glClear'
/usr/src/debug/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/git/main_glesv1.cpp:81: error: undefined reference to 'glMatrixMode'
/usr/src/debug/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/git/main_glesv1.cpp:82: error: undefined reference to 'glLoadIdentity'
/usr/src/debug/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/git/main_glesv1.cpp:84: error: undefined reference to 'glColor4f'
/usr/src/debug/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/git/main_glesv1.cpp:86: error: undefined reference to 'glEnableClientState'
/usr/src/debug/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/git/main_glesv1.cpp:88: error: undefined reference to 'glDisableClientState'
/usr/src/debug/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/git/main_glesv1.cpp:73: error: undefined reference to 'glVertexPointer'
/usr/src/debug/sdl2-opengles-test/1.0.6+gitrAUTOINC+40041a4e34-r0/git/main_glesv1.cpp:74: error: undefined reference to 'glDrawArrays'
collect2: error: ld returned 1 exit status
make: *** [makefile:19: sdl2_opengles1_test] Error 1
ERROR: oe_runmake failed

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>