audiosystem-passthrough: use BSD-3-Clause instead of ambiguous BSD
* fixes:
  ERROR: audiosystem-passthrough-1.2.1+gitAUTOINC+3165200ce2-r0 do_populate_lic: QA Issue: audiosystem-passthrough: No generic license file exists for: BSD in any provider [license-exists]

  after ambiguous BSD license text was removed in:
  https://git.openembedded.org/openembedded-core/commit/?h=kirkstone&id=14d4c007c49652d836d325a12bdbcd3bfa42e6d5

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>