classes: drop unused webos_qmake5, webos_prerelease_dep, webos_preferred_gfx_image_format, webos_localization_resources_dir
* fixes builds with too long sstate names:
  http://jenkins.nas-admin.org/job/LuneOS/view/testing/job/luneos-testing_mako/707/console

ERROR: org.webosports.app.firstuse-0.3.0-7+gitAUTOINC+4b9bc6cfa3-r0 do_convert_webos_preferred_gfx_image_format: Execution of event handler 'sstate_eventhandler' failed
Traceback (most recent call last):
  File "/home/jenkins/workspace/luneos-testing/webos-ports/openembedded-core/meta/classes/sstate.bbclass", line 1094, in sstate_eventhandler(e=<bb.build.TaskSucceeded object at 0x7fd101ce7cc0>):
             sstatepkg = d.getVar('SSTATE_PKG')
    >        bb.siggen.dump_this_task(sstatepkg + '_' + taskname + ".tgz" ".siginfo", d)
     }
  File "/home/jenkins/workspace/luneos-testing/webos-ports/bitbake/lib/bb/siggen.py", line 648, in dump_this_task(outfile='/home/jenkins/workspace/luneos-testing/webos-ports/sstate-cache/c4/sstate:org.webosports.app.firstuse:cortexa8t2hf-neon-halium-webos-linux-gnueabi:0.3.0-7+gitAUTOINC+4b9bc6cfa3:r0:cortexa8t2hf-neon-halium:3:c41aee12beed9882e8158660875bd1fe9052d42760f908da04cd880bcece9b0b_convert_webos_preferred_gfx_image_format.tgz.siginfo', d=<bb.data_smart.DataSmart object at 0x7fd1080e2c18>):
         referencestamp = bb.build.stamp_internal(task, d, None, True)
    >    bb.parse.siggen.dump_sigtask(fn, task, outfile, "customfile:" + referencestamp)

  File "/home/jenkins/workspace/luneos-testing/webos-ports/openembedded-core/meta/lib/oe/sstatesig.py", line 202, in SignatureGeneratorOEBasicHash.dump_sigtask(fn='/home/jenkins/workspace/luneos-testing/webos-ports/meta-webos-ports/meta-luneos/recipes-luneos/apps/org.webosports.app.firstuse.bb', task='do_convert_webos_preferred_gfx_image_format', stampbase='/home/jenkins/workspace/luneos-testing/webos-ports/sstate-cache/c4/sstate:org.webosports.app.firstuse:cortexa8t2hf-neon-halium-webos-linux-gnueabi:0.3.0-7+gitAUTOINC+4b9bc6cfa3:r0:cortexa8t2hf-neon-halium:3:c41aee12beed9882e8158660875bd1fe9052d42760f908da04cd880bcece9b0b_convert_webos_preferred_gfx_image_format.tgz.siginfo', runtime='customfile:/home/jenkins/workspace/luneos-testing/webos-ports/tmp-glibc/stamps/cortexa8t2hf-neon-halium-webos-linux-gnueabi/org.webosports.app.firstuse/0.3.0-7+gitAUTOINC+4b9bc6cfa3-r0'):
                 return
    >        super(bb.siggen.SignatureGeneratorBasicHash, self).dump_sigtask(fn, task, stampbase, runtime)

  File "/home/jenkins/workspace/luneos-testing/webos-ports/bitbake/lib/bb/siggen.py", line 374, in SignatureGeneratorOEBasicHash.dump_sigtask(fn='/home/jenkins/workspace/luneos-testing/webos-ports/meta-webos-ports/meta-luneos/recipes-luneos/apps/org.webosports.app.firstuse.bb', task='do_convert_webos_preferred_gfx_image_format', stampbase='/home/jenkins/workspace/luneos-testing/webos-ports/sstate-cache/c4/sstate:org.webosports.app.firstuse:cortexa8t2hf-neon-halium-webos-linux-gnueabi:0.3.0-7+gitAUTOINC+4b9bc6cfa3:r0:cortexa8t2hf-neon-halium:3:c41aee12beed9882e8158660875bd1fe9052d42760f908da04cd880bcece9b0b_convert_webos_preferred_gfx_image_format.tgz.siginfo', runtime='customfile:/home/jenkins/workspace/luneos-testing/webos-ports/tmp-glibc/stamps/cortexa8t2hf-neon-halium-webos-linux-gnueabi/org.webosports.app.firstuse/0.3.0-7+gitAUTOINC+4b9bc6cfa3-r0'):
                     pass
    >            raise err

  File "/home/jenkins/workspace/luneos-testing/webos-ports/bitbake/lib/bb/siggen.py", line 368, in SignatureGeneratorOEBasicHash.dump_sigtask(fn='/home/jenkins/workspace/luneos-testing/webos-ports/meta-webos-ports/meta-luneos/recipes-luneos/apps/org.webosports.app.firstuse.bb', task='do_convert_webos_preferred_gfx_image_format', stampbase='/home/jenkins/workspace/luneos-testing/webos-ports/sstate-cache/c4/sstate:org.webosports.app.firstuse:cortexa8t2hf-neon-halium-webos-linux-gnueabi:0.3.0-7+gitAUTOINC+4b9bc6cfa3:r0:cortexa8t2hf-neon-halium:3:c41aee12beed9882e8158660875bd1fe9052d42760f908da04cd880bcece9b0b_convert_webos_preferred_gfx_image_format.tgz.siginfo', runtime='customfile:/home/jenkins/workspace/luneos-testing/webos-ports/tmp-glibc/stamps/cortexa8t2hf-neon-halium-webos-linux-gnueabi/org.webosports.app.firstuse/0.3.0-7+gitAUTOINC+4b9bc6cfa3-r0'):
                 os.chmod(tmpfile, 0o664)
    >            os.rename(tmpfile, sigfile)
             except (OSError, IOError) as err:
OSError: [Errno 36] File name too long: '/home/jenkins/workspace/luneos-testing/webos-ports/sstate-cache/c4/sigtask.e90lrqbb' -> '/home/jenkins/workspace/luneos-testing/webos-ports/sstate-cache/c4/sstate:org.webosports.app.firstuse:cortexa8t2hf-neon-halium-webos-linux-gnueabi:0.3.0-7+gitAUTOINC+4b9bc6cfa3:r0:cortexa8t2hf-neon-halium:3:c41aee12beed9882e8158660875bd1fe9052d42760f908da04cd880bcece9b0b_convert_webos_preferred_gfx_image_format.tgz.siginfo'

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>