meta-luneos: exclude ofono-conf from signatures as abi safe
* fixes:
ERROR: ofono different signature for task do_package_write_ipk.sigdata between hammerhead and mako
runtaskdeps changed:
ofono/ofono-conf.bb.do_packagedata with hash 5c586161deec0e2b5d41a6bdebcb4471
 changed to
ofono/ofono-conf.bb.do_packagedata with hash db09acb87c752822a95cda7753c8f190
Hash for dependent task ofono/ofono-conf.bb.do_packagedata changed from 5c586161deec0e2b5d41a6bdebcb4471 to db09acb87c752822a95cda7753c8f190

as detected in:
http://jenkins.nas-admin.org/view/luneos-testing/job/luneos-testing_workspace-compare-signatures/11/console

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>