com.webos.service.mediarecorder: update from OSE v2.28.0
* needed to still build test-apps

ERROR: luneos-dev-image-1.0-r0 do_rootfs: Unable to install packages. Command '/OE/build/luneos-walnascar/tmp/work/qemux86_64-webos-linux/luneos-dev-image/1.0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /OE/build/luneos-walnascar/tmp/work/qemux86_64-webos-linux/luneos-dev-image/1.0/opkg.conf -t /OE/build/luneos-walnascar/tmp/work/qemux86_64-webos-linux/luneos-dev-image/1.0/temp/ipktemp/ -o /OE/build/luneos-walnascar/tmp/work/qemux86_64-webos-linux/luneos-dev-image/1.0/rootfs  --force-postinstall --prefer-arch-to-version   --add-ignore-recommends update-rc.d install base-passwd glmark2 kernel-modules libdrm-tests libegl-mesa libgbm libglapi libgles1-mesa libgles2-mesa mesa-megadriver opkg packagegroup-core-boot packagegroup-core-ssh-openssh packagegroup-luneos-development packagegroup-luneos-extended packagegroup-webos-extended qtbase-examples qtbase-plugins run-postinsts shadow' returned 1:
Solver encountered 1 problem(s):
Problem 1/1:
  - package packagegroup-webos-extended-1.0-r0.0.qemux86_64 requires com.webos.service.mediarecorder, but none of the providers can be installed
  - conflicting requests
  - nothing provides com.webos.service.mediarecorder-test-apps needed by com.webos.service.mediarecorder-1.0.0-17-r4.1.corei7-64

Solution 1:
  - do not ask to install a package providing packagegroup-webos-extended

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>