luna-sysmgr-ipc-messages: drop unnecessary DEPENDS
* it doesn't depend oin them, it will only install header files
* see:
  http://lists.openembedded.org/pipermail/openembedded-devel/2015-September/103271.html
* fixes:
ERROR: luna-sysmgr-ipc-messages different signature for task do_configure.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['autoconfautoconf_2.69.bb.do_populate_sysroot:virtual:native', 'automakeautomake_1.15.bb.do_populate_sysroot:virtual:native', 'cmake-modules-webos-nativecmake-modules-webos-native.bb.do_populate_sysroot', 'cmakecmake-native_3.3.1.bb.do_populate_sysroot', 'gnu-configgnu-config_git.bb.do_populate_sysroot:virtual:native', 'libtoollibtool-native_2.4.6.bb.do_populate_sysroot', 'luna-sysmgr-ipc-messagesluna-sysmgr-ipc-messages.bb.do_generate_toolchain_file', 'luna-sysmgr-ipc-messagesluna-sysmgr-ipc-messages.bb.do_patch', 'luna-sysmgr-ipcluna-sysmgr-ipc.bb.do_populate_sysroot', 'luna-webkit-apiluna-webkit-api.bb.do_populate_sysroot'] to ['autoconfautoconf_2.69.bb.do_populate_sysroot:virtual:native', 'automakeautomake_1.15.bb.do_populate_sysroot:virtual:native', 'cmake-modules-webos-nativecmake-modules-webos-native.bb.do_populate_sysroot', 'cmakecmake-native_3.3.1.bb.do_populate_sysroot', 'gnu-configgnu-config_git.bb.do_populate_sysroot:virtual:native', 'libtoollibtool-native_2.4.6.bb.do_populate_sysroot', 'luna-sysmgr-ipc-messagesluna-sysmgr-ipc-messages.bb.do_generate_toolchain_file', 'luna-sysmgr-ipc-messagesluna-sysmgr-ipc-messages.bb.do_patch', 'luna-sysmgr-ipcluna-sysmgr-ipc.bb.do_populate_sysroot', 'luna-webkit-apiluna-webkit-api.bb.do_populate_sysroot']
meta-webos-ports/meta-luneui/recipes-webos/luna-sysmgr-ipc/luna-sysmgr-ipc.bb.do_populate_sysroot with hash cc3eba3201ec35b42766c06ca2bc7afe
 changed to
meta-webos-ports/meta-luneui/recipes-webos/luna-sysmgr-ipc/luna-sysmgr-ipc.bb.do_populate_sysroot with hash f228ab5624346d79f348b5ada8e493c4
Hash for dependent task luna-sysmgr-ipcluna-sysmgr-ipc.bb.do_populate_sysroot changed from cc3eba3201ec35b42766c06ca2bc7afe to f228ab5624346d79f348b5ada8e493c4

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>