org.webosports.service.ipkg: webos-telephonyd: Fix missing return values
* fixes return-mismatch issues which are fatal by default with gcc-14

* org.webosports.service.ipkg

oe-service/src/luna_methods.c:812:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
oe-service/src/luna_methods.c:1532:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
oe-service/src/luna_methods.c:1929:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
oe-service/src/luna_methods.c:2006:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
oe-service/src/luna_methods.c:2057:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
oe-service/src/luna_methods.c:2137:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
oe-service/src/luna_methods.c:2217:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]

* webos-telephonyd

src/telephonyservice_call.c:46:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_call.c:96:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_call.c:142:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_call.c:188:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:129:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:135:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:186:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:192:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:213:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:219:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:244:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:295:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:346:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:398:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:457:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:557:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:563:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>