webos*.inc: Drop PACKAGE_ARCH overrides for packagegroups
* It was resolved in oe-core 1.7 which requires PACKAGE_ARCH to be set
  after allarch inherit.
* Fixes following ERRORs:
  ERROR: Please ensure recipe meta-qt5/recipes-qt/packagegroups/packagegroup-qt5-qtcreator-debug.bb sets PACKAGE_ARCH before inherit packagegroup
  ERROR: Please ensure recipe meta-oe/meta-oe/recipes-graphics/packagegroups/packagegroup-fonts-truetype.bb sets PACKAGE_ARCH before inherit packagegroup
  ERROR: Please ensure recipe oe-core/meta/recipes-core/packagegroups/packagegroup-core-standalone-sdk-target.bb sets PACKAGE_ARCH before inherit packagegroup
  ERROR: Please ensure recipe oe-core/meta/recipes-core/packagegroups/packagegroup-core-nfs.bb sets PACKAGE_ARCH before inherit packagegroup
  ERROR: Please ensure recipe oe-core/meta/recipes-core/packagegroups/packagegroup-core-ssh-dropbear.bb sets PACKAGE_ARCH before inherit packagegroup
  ERROR: Please ensure recipe oe-core/meta/recipes-core/packagegroups/packagegroup-core-ssh-openssh.bb sets PACKAGE_ARCH before inherit packagegroup
  ERROR: Please ensure recipe oe-core/meta/recipes-core/packagegroups/packagegroup-core-eclipse-debug.bb sets PACKAGE_ARCH before inherit packagegroup

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>