systemd: update patches to apply on v257
Upgraded in:
https://git.openembedded.org/openembedded-core/commit/?id=4891f47cdaf919033bf1c02cc12e4805e5db99a0

ERROR: Applying patch '0002-Add-webos-interface.patch' on target directory 'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/systemd/257.1/git'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/systemd/257.1/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0002-Add-webos-interface.patch
patching file src/oom/com.webos.MemoryManager1.conf
patching file src/oom/meson.build
patching file src/oom/oomd-manager.c
Hunk #1 FAILED at 16.
Hunk #2 succeeded at 394 (offset -3 lines).
Hunk #3 succeeded at 520 (offset -3 lines).
1 out of 3 hunks FAILED -- rejects in file src/oom/oomd-manager.c
patching file src/oom/oomd.c
Hunk #2 succeeded at 224 (offset 35 lines).
patching file src/oom/webos-manager-bus.c
patching file src/oom/webos-manager-bus.h
patching file src/oom/webos-manager.c
patching file src/oom/webos-manager.h
patching file units/systemd-oomd.service.in
Patch 0002-Add-webos-interface.patch does not apply (enforce with -f)

stderr: ')