oebackports: buildcfg: get_metadata_git_*: catch also bb.process.NotFoundError
apply the changes as in:
https://lists.openembedded.org/g/openembedded-core/message/214966

to fix parsing issues shown in:
https://layers.openembedded.org/layerindex/updates/42833/
like:

ERROR: Unable to read /opt/workdir/https___github_com_webOS-ports_meta-webos-ports/meta-luneos/recipes-core/images/luneos-emulator-appliance.bb: Traceback (most recent call last):
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/process.py", line 169, in run
    pipe = Popen(cmd, **options)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/process.py", line 73, in __init__
    subprocess.Popen.__init__(self, *args, **options)
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpxulqigs8/../common/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/data_smart.py", line 463, in expandWithRefs
    s = __expand_python_regexp__.sub(varparse.python_sub, s)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/data_smart.py", line 153, in python_sub
    value = utils.better_eval(codeobj, DataContext(self.d), {'d' : self.d})
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/utils.py", line 434, in better_eval
    return eval(source, ctx, locals)
  File "Var <WEBOS_DISTRO_TOPDIR_BRANCH>", line 1, in <module>
  File "/opt/workdir/git___git_openembedded_org_openembedded-core/meta/lib/oe/buildcfg.py", line 19, in get_metadata_git_branch
    rev, _ = bb.process.run('git rev-parse --abbrev-ref HEAD', cwd=path)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/process.py", line 172, in run
    raise NotFoundError(cmd)
bb.process.NotFoundError: Execution of 'git rev-parse --abbrev-ref HEAD' failed: command not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/command.py", line 90, in runCommand
    result = command_method(self, commandline)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/command.py", line 592, in parseRecipeFile
    envdata = command.cooker.databuilder._parse_recipe(config_data, fn, appendfiles, mc, layername)[cls]
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/cookerdata.py", line 507, in _parse_recipe
    return bb.parse.handle(bbfile, bb_data)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/__init__.py", line 119, in handle
    return h['handle'](fn, data, include, baseconfig)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/parse_py/BBHandler.py", line 158, in handle
    return ast.multi_finalize(fn, d)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/ast.py", line 460, in multi_finalize
    finalize(fn, d)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/ast.py", line 408, in finalize
    runAnonFuncs(d)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/ast.py", line 385, in runAnonFuncs
    bb.utils.better_exec("\n".join(code), {"d": d})
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/utils.py", line 409, in better_exec
    exec(code, get_context(), context)
  File "<code>", line 10, in <module>
  File "/opt/workdir/git___git_openembedded_org_openembedded-core/meta/classes-recipe/image-artifact-names.bbclass", line 37, in __anon_41__opt_workdir_git___git_openembedded_org_openembedded_core_meta_classes_recipe_image_artifact_names_bbclass
    if bb.data.inherits_class('deploy', d) and d.getVar("IMAGE_VERSION_SUFFIX") == "-${DATETIME}":
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/data_smart.py", line 659, in getVar
    return self.getVarFlag(var, "_content", expand, noweakdefault, parsing)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/data_smart.py", line 859, in getVarFlag
    parser = self.expandWithRefs(value, cachename)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/data_smart.py", line 461, in expandWithRefs
    s = __expand_var_regexp__.sub(varparse.var_sub, s)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/data_smart.py", line 113, in var_sub
    var = self.d.getVarFlag(key, "_content")
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/data_smart.py", line 859, in getVarFlag
    parser = self.expandWithRefs(value, cachename)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/data_smart.py", line 461, in expandWithRefs
    s = __expand_var_regexp__.sub(varparse.var_sub, s)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/data_smart.py", line 113, in var_sub
    var = self.d.getVarFlag(key, "_content")
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/data_smart.py", line 859, in getVarFlag
    parser = self.expandWithRefs(value, cachename)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/data_smart.py", line 479, in expandWithRefs
    raise ExpansionError(varname, s, exc).with_traceback(tb) from exc
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/data_smart.py", line 463, in expandWithRefs
    s = __expand_python_regexp__.sub(varparse.python_sub, s)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/data_smart.py", line 153, in python_sub
    value = utils.better_eval(codeobj, DataContext(self.d), {'d' : self.d})
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/utils.py", line 434, in better_eval
    return eval(source, ctx, locals)
  File "Var <WEBOS_DISTRO_TOPDIR_BRANCH>", line 1, in <module>
  File "/opt/workdir/git___git_openembedded_org_openembedded-core/meta/lib/oe/buildcfg.py", line 19, in get_metadata_git_branch
    rev, _ = bb.process.run('git rev-parse --abbrev-ref HEAD', cwd=path)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/process.py", line 172, in run
    raise NotFoundError(cmd)
bb.data_smart.ExpansionError: Failure expanding variable WEBOS_DISTRO_TOPDIR_BRANCH, expression was ${@oe.buildcfg.get_metadata_git_branch('/tmp/tmpxulqigs8/../common/').strip()} which triggered exception NotFoundError: Execution of 'git rev-parse --abbrev-ref HEAD' failed: command not found

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>