luneos-{package,emulator-appliance}: exclude DATETIME from signatures
* newer oe-core is a bit more strict about signatures being changed during the build
  and current builds fail with error like this:
  ERROR: luneos-dev-emulator-appliance-1.0-r0 do_deploy: Taskhash mismatch 9f927171878b77e05e7152334df62c7b verses a4d65adadf3d532c4b57cced78ab852b for /OE/buil
  ERROR: Taskhash mismatch 9f927171878b77e05e7152334df62c7b verses a4d65adadf3d532c4b57cced78ab852b for /OE/build/owpb/webos-ports/meta-webos-ports/meta-luneos/recipes-core/images/luneos-dev-emulator-appliance.bb.do_deploy

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>