bluetooth-sil-bluez5: use python3native and depend on python3-packaging-native
python3-packaging-native is used by gdbus-codegen. Fix it
similarly as gattlib in:
https://git.openembedded.org/meta-openembedded/commit/?id=8c5720df4a1f4ea0f72196029aae495fd58565b2

Fixes:
http://gecko.lge.com:8000/Errors/Details/788323

Traceback (most recent call last):
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-84/recipe-sysroot-native/usr/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-84/recipe-sysroot-native/usr/share/glib-2.0/codegen/codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-84/recipe-sysroot-native/usr/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-84/recipe-sysroot-native/usr/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
CMake Error at CMakeLists.txt:80 (message):
  Error in generating code for bluez5 dbus interface using gdbus-codegen

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>