pulseaudio-distro-conf: use MACHINE_ARCH
* as detected in
  http://jenkins.nas-admin.org/view/luneos-testing/job/luneos-testing_workspace-compare-signatures/11/console

ERROR: pulseaudio-distro-conf different signature for task do_populate_sysroot.sigdata between hammerhead and mako
Task dependencies changed from:
['ABIEXTENSION', 'AR', 'ARMPKGARCH', 'ARMPKGARCH_tune-armv7athf-neon', 'ARMPKGSFX_DSP', 'ARMPKGSFX_EABI', 'ARMPKGSFX_ENDIAN', 'ARMPKGSFX_FPU', 'ARMPKGSFX_THUMB', 'ARM_INSTRUCTION_SET', 'ARM_M_OPT', 'ARM_THUMB_OPT', 'ARM_THUMB_SUFFIX', 'AS', 'ASNEEDED', 'BB_CURRENTTASK', 'BUILD_AR', 'BUILD_AS', 'BUILD_AS_ARCH', 'BUILD_CC', 'BUILD_CCLD', 'BUILD_CC_ARCH', 'BUILD_CFLAGS', 'BUILD_CPP', 'BUILD_CPPFLAGS', 'BUILD_CXX', 'BUILD_CXXFLAGS', 'BUILD_FC', 'BUILD_LD', 'BUILD_LDFLAGS', 'BUILD_LD_ARCH', 'BUILD_NM', 'BUILD_OPTIMIZATION', 'BUILD_PREFIX', 'BUILD_RANLIB', 'BUILD_STRIP', 'CC', 'CCLD', 'CFLAGS', 'COMPONENTS_DIR', 'CPP', 'CPPFLAGS', 'CXX', 'CXXFLAGS', 'D', 'DEBUG_BUILD', 'DEBUG_FLAGS', 'DEBUG_OPTIMIZATION', 'DEBUG_PREFIX_MAP', 'DEFAULTTUNE', 'EXTENDPE', 'FC', 'FULL_OPTIMIZATION', 'HOST_AS_ARCH', 'HOST_CC_ARCH', 'HOST_LD_ARCH', 'HOST_PREFIX', 'INHIBIT_SYSROOT_STRIP', 'LC_ALL', 'LD', 'LDFLAGS', 'LIBCEXTENSION', 'LINKER_HASH_STYLE', 'MAKE', 'MULTIMACH_TARGET_SYS', 'NM', 'OBJCOPY', 'OBJDUMP', 'P', 'PACKAGE_ARCH', 'PE', 'PKG_CONFIG_DIR', 'PKG_CONFIG_DISABLE_UNINSTALLED', 'PKG_CONFIG_LIBDIR', 'PKG_CONFIG_PATH', 'PKG_CONFIG_SYSROOT_DIR', 'PKG_CONFIG_SYSTEM_INCLUDE_PATH', 'PKG_CONFIG_SYSTEM_LIBRARY_PATH', 'PN', 'PR', 'PROVIDES', 'PSEUDO_DISABLED', 'PV', 'QA_LOGFILE', 'RANLIB', 'READELF', 'RECIPE_SYSROOT', 'RECIPE_SYSROOT_NATIVE', 'SELECTED_OPTIMIZATION', 'SSTATECLEANFUNCS', 'SSTATECREATEFUNCS', 'SSTATEPOSTCREATEFUNCS', 'SSTATEPOSTINSTFUNCS', 'SSTATEPOSTUNPACKFUNCS', 'SSTATE_BUILDDIR', 'SSTATE_EXTRAPATH', 'SSTATE_INSTDIR', 'SSTATE_MANIFESTS', 'SSTATE_MANMACH', 'SSTATE_PKG', 'SSTATE_PKGNAME', 'SSTATE_PKGSPEC', 'SSTATE_SKIP_CREATION', 'SSTATE_VERSION', 'STAGING_BASE_LIBDIR_NATIVE', 'STAGING_DATADIR', 'STAGING_DIR', 'STAGING_DIR_NATIVE', 'STAGING_INCDIR_NATIVE', 'STAGING_LIBDIR_NATIVE', 'STAMP', 'STAMPS_DIR', 'STRINGS', 'STRIP', 'SYSROOT_DESTDIR', 'SYSROOT_DIRS', 'SYSROOT_DIRS_BLACKLIST', 'SYSROOT_PREPROCESS_FUNCS', 'TARGET_ARCH', 'TARGET_AS_ARCH', 'TARGET_CC_ARCH', 'TARGET_CFLAGS', 'TARGET_CPPFLAGS', 'TARGET_CXXFLAGS', 'TARGET_LDFLAGS', 'TARGET_LD_ARCH', 'TARGET_LINK_HASH_STYLE', 'TARGET_OS', 'TARGET_PREFIX', 'TARGET_SYS', 'TARGET_VENDOR', 'TOOLCHAIN_OPTIONS', 'TUNE_ASARGS', 'TUNE_CCARGS', 'TUNE_CCARGS_MFLOAT', 'TUNE_CCARGS_MFPU', 'TUNE_FEATURES', 'TUNE_FEATURES_tune-armv7a', 'TUNE_FEATURES_tune-armv7at', 'TUNE_FEATURES_tune-armv7at-neon', 'TUNE_FEATURES_tune-armv7athf-neon', 'TUNE_LDARGS', 'TUNE_PKGARCH', 'base_bindir', 'base_libdir', 'base_libdir_native', 'base_prefix', 'base_sbindir', 'baselib', 'bindir', 'datadir', 'do_populate_sysroot[sstate-fixmedir]', 'do_populate_sysroot[sstate-inputdirs]', 'do_populate_sysroot[umask]', 'do_qa_staging', 'docdir', 'exec_prefix', 'generate_sstatefn', 'includedir', 'includedir_native', 'infodir', 'libdir', 'libdir_native', 'libexecdir', 'localstatedir', 'mandir', 'nonarch_base_libdir', 'nonarch_libdir', 'oldincludedir', 'package_qa_check_staged', 'package_qa_handle_error', 'package_qa_write_error', 'prefix', 'prefix_native', 'sbindir', 'servicedir', 'sharedstatedir', 'sstate_add', 'sstate_clean', 'sstate_clean_manifest', 'sstate_init', 'sstate_install', 'sstate_installpkgdir', 'sstate_package', 'sstate_state_fromvars', 'sstate_task_postfunc', 'sstate_task_prefunc', 'sysconfdir', 'sysroot_stage_all', 'sysroot_stage_dir', 'sysroot_stage_dirs', 'sysroot_strip', 'systemd_system_unitdir', 'systemd_unitdir', 'systemd_user_unitdir']
to:
['ABIEXTENSION', 'AR', 'ARMPKGARCH', 'ARMPKGARCH_tune-armv7athf-neon', 'ARMPKGSFX_DSP', 'ARMPKGSFX_EABI', 'ARMPKGSFX_ENDIAN', 'ARMPKGSFX_FPU', 'ARMPKGSFX_THUMB', 'ARM_INSTRUCTION_SET', 'ARM_M_OPT', 'ARM_THUMB_OPT', 'ARM_THUMB_SUFFIX', 'AS', 'ASNEEDED', 'BB_CURRENTTASK', 'BUILD_AR', 'BUILD_AS', 'BUILD_AS_ARCH', 'BUILD_CC', 'BUILD_CCLD', 'BUILD_CC_ARCH', 'BUILD_CFLAGS', 'BUILD_CPP', 'BUILD_CPPFLAGS', 'BUILD_CXX', 'BUILD_CXXFLAGS', 'BUILD_FC', 'BUILD_LD', 'BUILD_LDFLAGS', 'BUILD_LD_ARCH', 'BUILD_NM', 'BUILD_OPTIMIZATION', 'BUILD_PREFIX', 'BUILD_RANLIB', 'BUILD_STRIP', 'CC', 'CCLD', 'CFLAGS', 'COMPONENTS_DIR', 'CPP', 'CPPFLAGS', 'CXX', 'CXXFLAGS', 'D', 'DEBUG_BUILD', 'DEBUG_FLAGS', 'DEBUG_OPTIMIZATION', 'DEBUG_PREFIX_MAP', 'DEFAULTTUNE', 'EXTENDPE', 'FC', 'FULL_OPTIMIZATION', 'HOST_AS_ARCH', 'HOST_CC_ARCH', 'HOST_LD_ARCH', 'HOST_PREFIX', 'INHIBIT_SYSROOT_STRIP', 'LC_ALL', 'LD', 'LDFLAGS', 'LIBCEXTENSION', 'LINKER_HASH_STYLE', 'MACHINE', 'MACHINE_ARCH', 'MAKE', 'MULTIMACH_TARGET_SYS', 'NM', 'OBJCOPY', 'OBJDUMP', 'P', 'PACKAGE_ARCH', 'PE', 'PKG_CONFIG_DIR', 'PKG_CONFIG_DISABLE_UNINSTALLED', 'PKG_CONFIG_LIBDIR', 'PKG_CONFIG_PATH', 'PKG_CONFIG_SYSROOT_DIR', 'PKG_CONFIG_SYSTEM_INCLUDE_PATH', 'PKG_CONFIG_SYSTEM_LIBRARY_PATH', 'PN', 'PR', 'PROVIDES', 'PSEUDO_DISABLED', 'PV', 'QA_LOGFILE', 'RANLIB', 'READELF', 'RECIPE_SYSROOT', 'RECIPE_SYSROOT_NATIVE', 'SELECTED_OPTIMIZATION', 'SSTATECLEANFUNCS', 'SSTATECREATEFUNCS', 'SSTATEPOSTCREATEFUNCS', 'SSTATEPOSTINSTFUNCS', 'SSTATEPOSTUNPACKFUNCS', 'SSTATE_BUILDDIR', 'SSTATE_EXTRAPATH', 'SSTATE_INSTDIR', 'SSTATE_MANIFESTS', 'SSTATE_MANMACH', 'SSTATE_PKG', 'SSTATE_PKGNAME', 'SSTATE_PKGSPEC', 'SSTATE_SKIP_CREATION', 'SSTATE_VERSION', 'STAGING_BASE_LIBDIR_NATIVE', 'STAGING_DATADIR', 'STAGING_DIR', 'STAGING_DIR_NATIVE', 'STAGING_INCDIR_NATIVE', 'STAGING_LIBDIR_NATIVE', 'STAMP', 'STAMPS_DIR', 'STRINGS', 'STRIP', 'SYSROOT_DESTDIR', 'SYSROOT_DIRS', 'SYSROOT_DIRS_BLACKLIST', 'SYSROOT_PREPROCESS_FUNCS', 'TARGET_ARCH', 'TARGET_AS_ARCH', 'TARGET_CC_ARCH', 'TARGET_CFLAGS', 'TARGET_CPPFLAGS', 'TARGET_CXXFLAGS', 'TARGET_LDFLAGS', 'TARGET_LD_ARCH', 'TARGET_LINK_HASH_STYLE', 'TARGET_OS', 'TARGET_PREFIX', 'TARGET_SYS', 'TARGET_VENDOR', 'TOOLCHAIN_OPTIONS', 'TUNE_ASARGS', 'TUNE_CCARGS', 'TUNE_CCARGS_MFLOAT', 'TUNE_CCARGS_MFPU', 'TUNE_FEATURES', 'TUNE_FEATURES_tune-armv7a', 'TUNE_FEATURES_tune-armv7at', 'TUNE_FEATURES_tune-armv7at-neon', 'TUNE_FEATURES_tune-armv7athf-neon', 'TUNE_LDARGS', 'TUNE_PKGARCH', 'base_bindir', 'base_libdir', 'base_libdir_native', 'base_prefix', 'base_sbindir', 'baselib', 'bindir', 'datadir', 'do_populate_sysroot[sstate-fixmedir]', 'do_populate_sysroot[sstate-inputdirs]', 'do_populate_sysroot[umask]', 'do_qa_staging', 'docdir', 'exec_prefix', 'generate_sstatefn', 'includedir', 'includedir_native', 'infodir', 'libdir', 'libdir_native', 'libexecdir', 'localstatedir', 'mandir', 'nonarch_base_libdir', 'nonarch_libdir', 'oldincludedir', 'package_qa_check_staged', 'package_qa_handle_error', 'package_qa_write_error', 'prefix', 'prefix_native', 'sbindir', 'servicedir', 'sharedstatedir', 'sstate_add', 'sstate_clean', 'sstate_clean_manifest', 'sstate_init', 'sstate_install', 'sstate_installpkgdir', 'sstate_package', 'sstate_state_fromvars', 'sstate_task_postfunc', 'sstate_task_prefunc', 'sysconfdir', 'sysroot_stage_all', 'sysroot_stage_dir', 'sysroot_stage_dirs', 'sysroot_strip', 'systemd_system_unitdir', 'systemd_unitdir', 'systemd_user_unitdir']
basehash changed from 6e44091fd7089a1b91e51edf2e2b1f5a to 7a4142e507b4ca9a4e00fdf31abdd132
List of dependencies for variable PACKAGE_ARCH changed from '{'TUNE_PKGARCH'}' to '{'MACHINE_ARCH'}'
changed items: {'MACHINE_ARCH', 'TUNE_PKGARCH'}
Dependency on variable MACHINE_ARCH was added
Dependency on variable MACHINE was added
Variable SSTATE_MANMACH value changed from 'armv7ahf-neon' to 'mako'
Variable PACKAGE_ARCH value changed from '${TUNE_PKGARCH}' to '${MACHINE_ARCH}'
runtaskdeps changed:
pulseaudio/pulseaudio-distro-conf_1.0.bb.do_install with hash dd445ea15eb56e949f1d9939e0480415
 changed to
pulseaudio/pulseaudio-distro-conf_1.0.bb.do_install with hash 0f01277ed60c05fe8f11f5dbdc5ab570
Hash for dependent task pulseaudio/pulseaudio-distro-conf_1.0.bb.do_install changed from dd445ea15eb56e949f1d9939e0480415 to 0f01277ed60c05fe8f11f5dbdc5ab570

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>