core-apps: drop allarch
* it depends on TUNE_PKGARCH bash
* fixes:
ERROR: core-apps different signature for task do_package_write_ipk.sigdata between hammerhead and qemux86
runtaskdeps changed:
bash/bash_4.3.30.bb.do_packagedata with hash 1ab50609063c7b7602619077d4aa1ee9
 changed to
bash/bash_4.3.30.bb.do_packagedata with hash 8a1b7d8717d0ae34765b8fbaed30add2
Hash for dependent task bash/bash_4.3.30.bb.do_packagedata changed from 1ab50609063c7b7602619077d4aa1ee9 to 8a1b7d8717d0ae34765b8fbaed30add2

as detected in:
http://jenkins.nas-admin.org/view/luneos-testing/job/luneos-testing_workspace-compare-signatures/11/console

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>