mtp-server: Add missing libhybris dependency
* fails with:
  mtp-server/0.0.1+bzr35-r0/trunk/src/MtpServer.cpp:42:42:
  fatal error: hybris/properties/properties.h: No such file or directory

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>