qtwayland: enable wayland-drm-egl-server-buffer
Without this new mesa-22 will try to use /usr/lib/dri/swrast_dri.so
instead of /usr/lib/dri/vmwgfx_dri.so as before.

There is a difference in behavior since:
https://gitlab.freedesktop.org/mesa/mesa/-/commit/83916ae0b9b#b91f29c819033a507b2cac556bea4f5aecd8893d_1589_1968

   /* The compositor must expose the dma-buf interface. */
   if (roundtrip(dri2_dpy) < 0 || dri2_dpy->wl_dmabuf == NULL)
      goto cleanup;

Now it will go to cleanup from here, instead of continue to load
preferred driver based on /dev/dri. Then it will go through
dri2_initialize_wayland_swrast, because of disp->Options.ForceSoftware:
https://gitlab.freedesktop.org/mesa/mesa/-/blob/83916ae0b9b920c521bf9bb3e5f82fb911b3a3cf/src/egl/drivers/dri2/platform_wayland.c#L2571

Compare the initialization sequence (with some extra debug output
added to libEGL):

==> lsm.log <==
LSM {"category":"startup"} Starting /usr/bin/surface-manager with flags -platform eglfs_webos ...
LSM {} (null), Using config file "/tmp/xdg/surface-manager.eglfs.json"
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/root/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/root/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/root/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/root/.drirc: No such file or directory.
libEGL warning: MJ: dri2_initialize
libEGL warning: MJ: dri2_initialize_drm
libEGL warning: MJ: gbm_device_get_backend_name drm
libEGL warning: MJ: dri2_load_driver
libEGL warning: MJ: dri2_open_driver from _EGLDisplay vmwgfx
libEGL debug: MESA-LOADER: dlopen(/usr/lib/dri/vmwgfx_dri.so)
libEGL debug: found extension `DRI_Core'
libEGL info: found extension DRI_Core version 2
libEGL debug: found extension `DRI_IMAGE_DRIVER'
libEGL debug: found extension `DRI_DRI2'
...
libEGL debug: No DRI config supports native format XB4H
libEGL debug: No DRI config supports native format AB4H
libEGL warning: MJ: dri2_initialize2 vmwgfx

==> wam.log <==
[INFO:app_runtime_browser_context.cc(66)] kUserDataDir is set.
[INFO:app_runtime_browser_context.cc(77)] Will use path=/var/lib/wam/Default
libEGL debug: Native platform type: wayland (autodetected)
libEGL warning: MJ: dri2_initialize
libEGL warning: MJ: dri2_initialize_wayland_drm
libEGL warning: MJ: before wl_display_create_queue -1
libEGL warning: MJ: wl_proxy_create_wrapper -1
libEGL warning: MJ: before wl_drm -1
libEGL warning: MJ: user_preferred_fd 50
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /var/lib/wam/.drirc: No such file or directory.
libEGL warning: MJ: driver from getenv: (null)
libEGL debug: using driver vmwgfx for 50
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /var/lib/wam/.drirc: No such file or directory.
libEGL debug: pci id for fd 50: 15ad:0405, driver vmwgfx
libEGL warning: MJ: dri2_load_driver_dri3
libEGL warning: MJ: dri2_open_driver from _EGLDisplay vmwgfx
libEGL debug: MESA-LOADER: dlopen(/usr/lib/dri/vmwgfx_dri.so)
libEGL debug: found extension `DRI_Core'
...
libEGL debug: No DRI config supports native format ABGR8888
libEGL debug: No DRI config supports native format XBGR8888
libEGL warning: MJ: dri2_initialize2 vmwgfx
libEGL debug: the value (0xd) of attribute 0x3040 did not meet the criteria (0x40)
libEGL debug: the value (0xd) of attribute 0x3040 did not meet the criteria (0x40)
libEGL debug: the value (0xd) of attribute 0x3040 did not meet the criteria (0x40)
libEGL debug: the value (0xd) of attribute 0x3040 did not meet the criteria (0x40)

==> wam-before-fix.log <==
[INFO:app_runtime_browser_context.cc(66)] kUserDataDir is set.
[INFO:app_runtime_browser_context.cc(77)] Will use path=/var/lib/wam/Default
libEGL debug: Native platform type: wayland (autodetected)
libEGL warning: MJ: dri2_initialize_wayland_drm
libEGL warning: MJ: before wl_display_create_queue -1
libEGL warning: MJ: wl_proxy_create_wrapper -1
libEGL warning: MJ: dma-buf interface -1
libEGL warning: MJ: dri2_open_driver from _EGLDisplay swrast
libEGL debug: MESA-LOADER: dlopen(/usr/lib/dri/swrast_dri.so)
libEGL debug: found extension `DRI_Core'
libEGL info: found extension DRI_Core version 2
libEGL debug: found extension `DRI_SWRast'
libEGL info: found extension DRI_SWRast version 4
libEGL debug: found extension `DRI_CopySubBuffer'
libEGL debug: found extension `DRI_ConfigOptions'
libEGL debug: found extension `DRI_Core'
libEGL debug: found extension `DRI_SWRast'
libEGL debug: found extension `DRI_CopySubBuffer'
libEGL debug: found extension `DRI_ConfigOptions'
...
libEGL debug: No DRI config supports native format ABGR8888
libEGL debug: No DRI config supports native format XBGR8888
...
[ERROR:gpu_channel_manager.cc(746)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[ERROR:shared_image_stub.cc(460)] SharedImageStub: unable to create context
[ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub

I've tried to enable drm ozone_platform in webruntime, but unfortunately
the ozone/aura_desktop integration doesn't seem to support it yet:

http://gecko.lge.com/Errors/Details/419040

FAILED: libcbe.so libcbe.so.TOC
TOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime/91.0.4472.114-18-r53.4/recipe-sysroot-native/usr/bin/python3-native/python3 "../../git/src/build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="nm"  --sofile="./libcbe.so" --tocfile="./libcbe.so.TOC" --output="./libcbe.so" -- x86_64-webos-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime/91.0.4472.114-18-r53.4/recipe-sysroot -shared -Wl,-soname="libcbe.so" -Wl,--build-id -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=gold -Wl,--threads -Wl,--thread-count=4 -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -LTOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime/91.0.4472.114-18-r53.4/recipe-sysrootTOPDIR/BUILD/work/qemux86_64-webos-linux/webos-wayland-extensions/1.0.0-43-r6/recipe-sysroot/usr/lib -o "./libcbe.so" @"./libcbe.so.rsp"
obj/ozone/ui/desktop_aura/views_ozone_wayland/desktop_factory_ozone_list.o:desktop_factory_ozone_list.cc:ui::PlatformConstructorList<views::DesktopFactoryOzone>::kConstructors: error: undefined reference to 'views::CreateDesktopFactoryOzoneDrm()'
collect2: error: ld returned 1 exit status

There is CreateDesktopFactoryOzone only for Headless, Egltest, Wayland, Wayland_external platforms.

And even changing src/ui/ozone/generate_constructor_list.py to generate just for Headless instead
of all enabled ozone platforms has own issues as well, so maybe it's not worth spending more time
on this now. It isn't resolved in 94 version as well and upstream chromium doesn't have
src/ozone/ui/desktop_aura at all, only src/ui/views/widget/desktop_aura, maybe worth re-investigating
later when upgrading to chromium with ozone fully integrated in upstream:
https://bugs.chromium.org/p/chromium/issues/detail?id=578890
in LGE fork this src/ozone/ui comes from neva/chromium 1.5:
https://github.com/webosose/chromium91/commit/7cef9376f8f6f59d7dc8f572716c1aaf28b3d9b2
and there is e.g. src/ozone/patches/0002-Adapt-DesktopFactoryOzone-to-respect-ozone-platform-.patch from 2015:
https://github.com/webosose/chromium91/blob/master/src/ozone/patches/0001-Browser-Support-Desktop-Aura-creation-on-Ozone.patch
which probably needs to be refreshed as well.

This issue is AFAIK only reproducible on emulator, on rpi4 it
was working OK with new mesa-22.