libgbinder: use gnu17 even with gcc-15
gcc-15 uses gnu23 standard for c since:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212
but this component isn't readly for it and fails to build.

src/gbinder_writer.c: In function 'gbinder_writer_alloc':
src/gbinder_writer.c:1318:60: error: passing argument 2 of 'gbinder_cleanup_add' from incompatible pointer type [-Wincompatible-pointer-types]
 1318 |         data->cleanup = gbinder_cleanup_add(data->cleanup, dealloc, ptr);
      |                                                            ^~~~~~~
      |                                                            |
      |                                                            void (*)(void)
In file included from src/gbinder_writer_p.h:38,
                 from src/gbinder_writer.c:33:
src/gbinder_cleanup.h:51:20: note: expected 'GDestroyNotify' {aka 'void (*)(void *)'} but argument is of type 'void (*)(void)'
   51 |     GDestroyNotify destroy,
      |     ~~~~~~~~~~~~~~~^~~~~~~
In file included from /OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/libgbinder/1.1.35/recipe-sysroot/usr/include/glib-2.0/glib/galloca.h:34,
                 from /OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/libgbinder/1.1.35/recipe-sysroot/usr/include/glib-2.0/glib.h:32,
                 from /OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/libgbinder/1.1.35/recipe-sysroot/usr/include/gutil/gutil_types.h:36,
                 from include/gbinder_types.h:36,
                 from include/gbinder_writer.h:36,
                 from src/gbinder_writer_p.h:36:
/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/libgbinder/1.1.35/recipe-sysroot/usr/include/glib-2.0/glib/gtypes.h:140:27: note: 'GDestroyNotify' declared here
  140 | typedef void            (*GDestroyNotify)       (gpointer       data);
      |                           ^~~~~~~~~~~~~~
src/gbinder_writer.c: In function 'gbinder_writer_malloc':
src/gbinder_writer.c:1329:55: error: passing argument 4 of 'gbinder_writer_alloc' from incompatible pointer type [-Wincompatible-pointer-types]
 1329 |     return gbinder_writer_alloc(self, size, g_malloc, g_free);
      |                                                       ^~~~~~
      |                                                       |
      |                                                       void (*)(void *)
src/gbinder_writer.c:1311:12: note: expected 'void (*)(void)' but argument is of type 'void (*)(void *)'
 1311 |     void (*dealloc)())
      |     ~~~~~~~^~~~~~~~~~
In file included from /OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/libgbinder/1.1.35/recipe-sysroot/usr/include/glib-2.0/glib/glist.h:34,
                 from /OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/libgbinder/1.1.35/recipe-sysroot/usr/include/glib-2.0/glib/ghash.h:36,
                 from /OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/libgbinder/1.1.35/recipe-sysroot/usr/include/glib-2.0/glib.h:52:
/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/libgbinder/1.1.35/recipe-sysroot/usr/include/glib-2.0/glib/gmem.h:74:11: note: 'g_free' declared here
   74 | void     (g_free)         (gpointer          mem);
      |           ^~~~~~
src/gbinder_writer.c: In function 'gbinder_writer_malloc0':
src/gbinder_writer.c:1337:56: error: passing argument 4 of 'gbinder_writer_alloc' from incompatible pointer type [-Wincompatible-pointer-types]
 1337 |     return gbinder_writer_alloc(self, size, g_malloc0, g_free);
      |                                                        ^~~~~~
      |                                                        |
      |                                                        void (*)(void *)
src/gbinder_writer.c:1311:12: note: expected 'void (*)(void)' but argument is of type 'void (*)(void *)'
 1311 |     void (*dealloc)())
      |     ~~~~~~~^~~~~~~~~~
/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/libgbinder/1.1.35/recipe-sysroot/usr/include/glib-2.0/glib/gmem.h:74:11: note: 'g_free' declared here
   74 | void     (g_free)         (gpointer          mem);
      |           ^~~~~~

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>