com.webos.service.battery: use gnu17 even with gcc-15
gcc-15 uses gnu23 standard for c since:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212
but this component isn't readly for it and fails to build.

com.webos.service.battery/1.0.0-1+git/git/batteryd/utils/uevent.c:88:9: error: too many arguments to function 'func'; expected 0, have 2

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>