nyx-modules-hybris: Add missing libhybris dependency
* fails with:
  nyx-modules-hybris/0.1.0+gitrAUTOINC+3c0dc8e01f-r0/git/src/device_info/device_info.c:30:42:
  fatal error: hybris/properties/properties.h: No such file or directory
  and
  nyx-modules-hybris/0.1.0+gitrAUTOINC+3c0dc8e01f-r0/git/src/led_controller/led_controller.c:54:
  error: undefined reference to 'hw_get_module'

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>