jsoncpp-clang: rename to match new recipe version
Updated in:
https://git.openembedded.org/meta-openembedded/commit/?id=f556659ec36275eca15bf4999e5daa7c5a44452e

Fixes:
ERROR: ParseError at recipes-devtools/jsoncpp/jsoncpp-clang_1.9.5.bb:3: Could not include required file recipes-devtools/jsoncpp/jsoncpp_1.9.5.bb
ERROR: Parsing halted due to errors, see error messages above