node-gyp-packages-native: use BPN instead of PN in SRC_URI
* fixes:
  ERROR: node-gyp-packages-native-0.12.2-r0 do_unpack: QA Issue: node-gyp-packages-native: SRC_URI uses PN not BPN [src-uri-bad]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>