python3-gbinder: set PV, use main branch with fix for newer python
* set PV to 1.0.0 instead of "git", based on git describe:
  python3-gbinder/git-r0/git $ git describe 1.0.0-1-g79d40e9

* use main branch, bullseye has 3 additional packaging changes for
  debian, but we don't need them and main has a fix for:

  DEBUG: Executing shell function do_compile
  Traceback (most recent call last):
    File "/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3-gbinder/git-r0/git/setup.py", line 22, in <module>
      extensions = [Extension('gbinder', **extension_kwargs)]
  TypeError: keywords must be strings
  ERROR: 'python3 setup.py bdist_wheel ' execution failed.

  python3-gbinder/git-r0/git $ git log --oneline cd7620aa0d2e8875785708ad4263808636f3dce5..79d40e9e564772973f7f085ed5c48e3fc625e0f5
  79d40e9 setup: Drop None from keywords

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>