python3-gbinder: inherit pkgconfig
* in honister we cannot replace DISTUTTILS_BUILD_ARGS with
  SETUPTOOLS_BUILD_ARGS, because it was changed only in kirkstone:
  https://git.openembedded.org/openembedded-core/commit/meta/classes/setuptools3.bbclass?h=kirkstone&id=ca73393a36c4144662ea8570f904154188e9815a

* add libglibutil dependency and more importantly pkgconfig inherit
  as without pkgconfig it will silently fail to add it in extension_kwargs
  and later fails with:
| building 'gbinder' extension
| x86_64-webos-linux-gcc -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3-gbinder/1.0.0+gitAUTOINC+79d40e9e56-r0/recipe-sysroot -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3/3.10.4-r0=/usr/src/debug/python3/3.10.4-r0 -fdebug-prefix-map=/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3/3.10.4-r0=/usr/src/debug/python3/3.10.4-r0 -fdebug-prefix-map=/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3-gbinder/1.0.0+gitAUTOINC+79d40e9e56-r0/recipe-sysroot= -fdebug-prefix-map=/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3-gbinder/1.0.0+gitAUTOINC+79d40e9e56-r0/recipe-sysroot-native= -DHAVE_BROKEN_POSIX_SEMAPHORES -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3/3.10.4-r0=/usr/src/debug/python3/3.10.4-r0 -fdebug-prefix-map=/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3/3.10.4-r0=/usr/src/debug/python3/3.10.4-r0 -fdebug-prefix-map=/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3-gbinder/1.0.0+gitAUTOINC+79d40e9e56-r0/recipe-sysroot= -fdebug-prefix-map=/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3-gbinder/1.0.0+gitAUTOINC+79d40e9e56-r0/recipe-sysroot-native= -DHAVE_BROKEN_POSIX_SEMAPHORES -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3-gbinder/1.0.0+gitAUTOINC+79d40e9e56-r0=/usr/src/debug/python3-gbinder/1.0.0+gitAUTOINC+79d40e9e56-r0 -fdebug-prefix-map=/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3-gbinder/1.0.0+gitAUTOINC+79d40e9e56-r0=/usr/src/debug/python3-gbinder/1.0.0+gitAUTOINC+79d40e9e56-r0 -fdebug-prefix-map=/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3-gbinder/1.0.0+gitAUTOINC+79d40e9e56-r0/recipe-sysroot= -fdebug-prefix-map=/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3-gbinder/1.0.0+gitAUTOINC+79d40e9e56-r0/recipe-sysroot-native= -fPIC -I/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3-gbinder/1.0.0+gitAUTOINC+79d40e9e56-r0/recipe-sysroot/usr/include/python3.10 -c gbinder.c -o build/temp.linux-x86_64-cpython-310/gbinder.o
| In file included from gbinder.c:709:
| /OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3-gbinder/1.0.0+gitAUTOINC+79d40e9e56-r0/recipe-sysroot/usr/include/gbinder/gbinder_types.h:36:10: fatal error: gutil_types.h: No such file or directory
|    36 | #include <gutil_types.h>
|       |          ^~~~~~~~~~~~~~~
| compilation terminated.
| error: command '/OE/build/luneos-langdale/webos-ports/tmp-glibc/work/core2-64-webos-linux/python3-gbinder/1.0.0+gitAUTOINC+79d40e9e56-r0/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-gcc' failed with exit code 1
| ERROR: 'python3 setup.py bdist_wheel sdist --cython' execution failed.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>