luneos-emulator-appliance: inherit image-artifact-names
* need to inherit it here, because it's no longer inheritted globally
  through buildhistory, but only for images since:
  https://git.openembedded.org/openembedded-core/commit/?id=4fdda4d6bd434c240ec1dfdbfc6eb7e25e2db1f3

  and causes:
ERROR: When reparsing /OE/build/luneos-langdale/webos-ports/meta-webos-ports/meta-luneos/recipes-core/images/luneos-dev-emulator-appliance.bb:do_deploy, the basehash value changed from 2b953bdba7964a486b3dc043381942765afecf8330c46e60c285aa3057b7cf0c to 7bdcc858a03fd0821278fcc97343cf5538ee898c04ba1a345e1496163a213cfb. The metadata is not deterministic and this needs to be fixed.
ERROR: The following commands may help:
ERROR: $ bitbake luneos-dev-emulator-appliance -cdo_deploy -Snone
ERROR: Then:
ERROR: $ bitbake luneos-dev-emulator-appliance -cdo_deploy -Sprintdiff

ERROR: Bitbake's cached basehash does not match the one we just generated (/OE/build/luneos-langdale/webos-ports/meta-webos-ports/meta-luneos/recipes-core/images/luneos-dev-emulator-appliance.bb:do_deploy)!
ERROR: The mismatched hashes were 2b953bdba7964a486b3dc043381942765afecf8330c46e60c285aa3057b7cf0c and 7bdcc858a03fd0821278fcc97343cf5538ee898c04ba1a345e1496163a213cfb
ERROR: Taskhash mismatch 5cec87e4edd9f39123efc160c5b77a5e770db49e7d064bb1a1c86627d40c08ee versus 881c1cd864395f0cda2cc4c29f39fd01a61f99199b54c676217b7343e1138d5a for /OE/build/luneos-langdale/webos-ports/meta-webos-ports/meta-luneos/recipes-core/images/luneos-dev-emulator-appliance.bb:do_deploy

bitbake-diffsigs tmp-glibc/stamps/qemux86_64-webos-linux/luneos-dev-emulator-appliance/1.0-r0.do_deploy.sigdata.[5f]*
NOTE: Starting bitbake server...
basehash changed from 7bdcc858a03fd0821278fcc97343cf5538ee898c04ba1a345e1496163a213cfb to 5191f8f66679062d43de44a92da7095e56fb8bf61152588be066e433c1a52d8e
Variable TIME value changed from '133639' to '145402'
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>