gstreamer1.0-plugins-bad: fix incompatible-pointer-types issue
These are fatal by default with gcc-14.

Fixes:
FAILED: ext/wayland/libgstwaylandsink.so.p/gstwaylandsink.c.o
ccache aarch64-webos-linux-gcc -mcpu=cortex-a72+crc -mbranch-protection=standard -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.11/recipe-sysroot -Iext/wayland/libgstwaylandsink.so.p -Iext/wayland -I../gst-plugins-bad-1.22.11/ext/wayland -I. -I../gst-plugins-bad-1.22.11 -Igst-libs -I../gst-plugins-bad-1.22.11/gst-libs -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.11/recipe-sysroot/usr/include/gstreamer-1.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.11/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.11/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.11/recipe-sysroot/usr/include/orc-0.4 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.11/recipe-sysroot/usr/include/libdrm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -fvisibility=hidden -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wmissing-prototypes -Wold-style-definition -Wmissing-declarations -Wredundant-decls -Wwrite-strings -Wformat -Wformat-security -Winit-self -Wmissing-include-dirs -Waddress -Wno-multichar -Wvla -Wpointer-arith -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.11/gst-plugins-bad-1.22.11=/usr/src/debug/gstreamer1.0-plugins-bad/1.22.11 -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.11/gst-plugins-bad-1.22.11=/usr/src/debug/gstreamer1.0-plugins-bad/1.22.11 -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.11/build=/usr/src/debug/gstreamer1.0-plugins-bad/1.22.11 -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.11/build=/usr/src/debug/gstreamer1.0-plugins-bad/1.22.11 -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.11/recipe-sysroot= -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.11/recipe-sysroot= -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.11/recipe-sysroot-native= -fPIC -pthread -DHAVE_CONFIG_H -DGST_USE_UNSTABLE_API -MD -MQ ext/wayland/libgstwaylandsink.so.p/gstwaylandsink.c.o -MF ext/wayland/libgstwaylandsink.so.p/gstwaylandsink.c.o.d -o ext/wayland/libgstwaylandsink.so.p/gstwaylandsink.c.o -c ../gst-plugins-bad-1.22.11/ext/wayland/gstwaylandsink.c
In file included from ../recipe-sysroot/usr/include/gstreamer-1.0/gst/gstbin.h:27,
                 from ../recipe-sysroot/usr/include/gstreamer-1.0/gst/gst.h:35,
                 from ../gst-plugins-bad-1.22.11/ext/wayland/gstwaylandsink.h:24,
                 from ../gst-plugins-bad-1.22.11/ext/wayland/gstwaylandsink.c:45:
../gst-plugins-bad-1.22.11/ext/wayland/gstwaylandsink.c: In function 'gst_wayland_sink_show_frame':
../gst-plugins-bad-1.22.11/ext/wayland/gstwaylandsink.c:1057:10: error: passing argument 1 of '_gst_element_error_printf' from incompatible pointer type [-Wincompatible-pointer-types]
 1057 |         (self, "failed to post video info message!"));
      |          ^~~~
      |          |
      |          GstWaylandSink * {aka struct _GstWaylandSink *}
../recipe-sysroot/usr/include/gstreamer-1.0/gst/gstelement.h:559:44: note: in definition of macro 'GST_ELEMENT_ERROR'
  559 |   gchar *__dbg = _gst_element_error_printf debug;                       \
      |                                            ^~~~~
Signed-off-by: Martin Jansa <martin.jansa@gmail.com>