luna-sysmgr: move /media/cryptofs/apps/var/lock creation back to pkg_postinst
* it was moved to do_install:append in:
  https://github.com/webOS-ports/meta-webos-ports/commit/d08cb7011c3a00f16a874e5de0f121517eaaa1d4

* use $D prefix to fix postinst execution in do_rootfs

* now causes:
  ERROR: luna-sysmgr-3.0.0-3+gitAUTOINC+c18ff49155-r0 do_package_qa: QA Issue: luna-sysmgr installs files in /media, but it is expected to be empty [empty-dirs]
  ERROR: luna-sysmgr-3.0.0-3+gitAUTOINC+c18ff49155-r0 do_package_qa: Fatal QA errors were found, failing task.
  ERROR: Logfile of failure stored in: /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/core2-64-webos-linux/luna-sysmgr/3.0.0-3+gitAUTOINC+c18ff49155-r0/temp/log.do_package_qa.606622

  webos-ports $ find tmp-glibc/work/core2-64-webos-linux/luna-sysmgr/3.0.0-3+gitAUTOINC+c18ff49155-r0/image/media/
  tmp-glibc/work/core2-64-webos-linux/luna-sysmgr/3.0.0-3+gitAUTOINC+c18ff49155-r0/image/media/
  tmp-glibc/work/core2-64-webos-linux/luna-sysmgr/3.0.0-3+gitAUTOINC+c18ff49155-r0/image/media/cryptofs
  tmp-glibc/work/core2-64-webos-linux/luna-sysmgr/3.0.0-3+gitAUTOINC+c18ff49155-r0/image/media/cryptofs/apps
  tmp-glibc/work/core2-64-webos-linux/luna-sysmgr/3.0.0-3+gitAUTOINC+c18ff49155-r0/image/media/cryptofs/apps/var
  tmp-glibc/work/core2-64-webos-linux/luna-sysmgr/3.0.0-3+gitAUTOINC+c18ff49155-r0/image/media/cryptofs/apps/var/lock

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>