connman-conf: drop wired-setup
* it's no longer very useful after:
  https://git.openembedded.org/openembedded-core/commit/?id=3c25b89720417a7b1963f0a32c870208a5803950

  and now causes:
  ERROR: connman-conf-1.0-r2 do_package: QA Issue: connman-conf: Files/directories were installed but not shipped in any package:
    /usr/share/connman
    /usr/share/connman/wired-setup
  Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
  connman-conf: 2 installed and not shipped files. [installed-vs-shipped]
  ERROR: connman-conf-1.0-r2 do_package: Fatal QA errors were found, failing task.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>