luna-webappmanager, org.webosports.app.browser: remove
* weren't updated since we switched from qtwebengine to webruntime
* fixes:
luneos-nanbield $ openembedded-core/scripts/sstate-diff-machines.sh --targets=world --tmpdir=tmp-glibc/ --analyze --machines="hammerhead mako qemux86-64" | tee log.compare-signatures
NOTE: Started PRServer with DBfile: /OE/build/luneos-nanbield/cache/prserv.sqlite3, Address: 127.0.0.1:43995, PID: 2446191
Loading cache...done.
Loaded 0 entries from dependency cache.
Parsing recipes...done.
Parsing of 3230 .bb files complete (0 cached, 3230 parsed). 5069 targets, 665 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'qtwebengine' (but /OE/build/luneos-nanbield/meta-webos-ports/meta-luneos/recipes-luneos/luna-webappmanager/luna-webappmanager.bb, /OE/build/luneos-nanbield/meta-qt6/recipes-qt/qt6/qtwebview_git.bb, /OE/build/luneos-nanbield/meta-webos-ports/meta-luneos/recipes-luneos/apps/org.webosports.app.browser.bb DEPENDS on or otherwise requires it)
qtwebengine was skipped: Recipe will be skipped because: qtwebengine is now replaced by WebOS OSE webruntime
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'luna-webappmanager', 'qtwebengine']

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>