extra-cmake-modules=v5.95.0
* fix PV, the old version wasn't 5.5.8, but 5.58.0
* use https protocol to fix:
  Fetching origin
  fatal: remote error: Please use the https: protocol to connect to anongit
  error: could not fetch origin
* upgrade to newer version with better licensing information from:
  https://invent.kde.org/frameworks/extra-cmake-modules/-/commit/110f62d69b9529a901889c3998817eb406a22c8f
* use specific BSD license to fix:
  ERROR: extra-cmake-modules-5.5.8+gitAUTOINC+307b36662e-r0 do_package: QA Issue: extra-cmake-modules: No generic license file exists for: BSD in any provider [license-exists]
  majority of what we use (tests are explicitly disabled) is under BSD-3-Clause:

  git $ git grep SPDX-License-Identifier | grep -v BSD-3-Clause
  .gitlab-ci.yml:# SPDX-License-Identifier: CC0-1.0
  .kde-ci.yml:# SPDX-License-Identifier: CC0-1.0
  find-modules/FindInotify.cmake:# SPDX-License-Identifier: BSD-2-Clause
  kde-modules/clang-format.cmake:# SPDX-License-Identifier: MIT
  modules/ECMCheckOutboundLicense.cmake:the SPDX marker ``SPDX-License-Identifier``.
  modules/ECMCheckOutboundLicense.cmake:    * All tested input source files must contain the SPDX-License-Identifier tag.
  modules/ECMCheckOutboundLicense.cmake:``FILES:``    : List of source files that contain valid SPDX-License-Identifier markers.
  modules/ECMQmlModule.cpp.in.license:SPDX-License-Identifier: CC0
  modules/ECMQmlModule.h.in.license:SPDX-License-Identifier: CC0
  tests/ECMCheckOutboundLicenseTest/testdata/BSD-2-Clause.cpp:    SPDX-License-Identifier: BSD-2-Clause
  tests/ECMCheckOutboundLicenseTest/testdata/GPL-2.0-only.cpp:    SPDX-License-Identifier: GPL-2.0-only
  tests/ECMCheckOutboundLicenseTest/testdata/GPL-2.0-or-later.cpp:    SPDX-License-Identifier: GPL-2.0-or-later
  tests/ECMCheckOutboundLicenseTest/testdata/GPL-3.0-only.cpp:    SPDX-License-Identifier: GPL-3.0-only
  tests/ECMCheckOutboundLicenseTest/testdata/LGPL-2.1-or-later.cpp:    SPDX-License-Identifier: LGPL-2.1-or-later
  tests/ECMCheckOutboundLicenseTest/testdata/LGPL-3.0-only.cpp:    SPDX-License-Identifier: LGPL-3.0-only
  tests/ECMQmlModuleTest/qmldir_expected_depends.license:SPDX-License-Identifier: CC0
  tests/ECMQmlModuleTest/qmldir_expected_full.license:SPDX-License-Identifier: CC0
  tests/ECMQmlModuleTest/qmldir_expected_qmlonly.license:SPDX-License-Identifier: CC0
  toolchain/generate-fastlane-metadata.py:# SPDX-License-Identifier: GPL-2.0-or-later

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>