luna-downloadmgr: Drop MACHINE specific configuration
Was used previously to pass specific MACHINE config, not used/needed anymore now. 

Also causes signature issues. So let's drop it for now. 

ERROR: luna-downloadmgr different signature for task do_configure.sigdata between hammerhead and mako
NOTE: Starting bitbake server...
basehash changed from b7cb5a7baac4e952eeeeb44126f4b12e8cd84bcbca48ef12b57d42a772fb63c4 to e78aba87dd45b7fffd1586ee4272edd7f0f13213aeab92b66def16ce58991962
Variable MACHINE value changed from 'hammerhead' to 'mako'

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>