qtbase: keep wayland PACKAGECONFIG enabled based on DISTRO_FEATURES
* separate PACKAGECONFIG for wayland was added in 6.7:
  https://codereview.qt-project.org/c/yocto/meta-qt6/+/543646

  but because we overwrite whole PACKAGECONFIG_GRAPHICS the default value
  wasn't updated in our builds causing qtwayland configure failure:

-- Configure summary:

Qt Wayland Client ........................ yes
Qt Wayland Compositor .................... yes
Qt Wayland Drivers:
  EGL .................................... yes
  Raspberry Pi ........................... no
  DRM EGL ................................ yes
  libhybris EGL .......................... no
  Linux dma-buf server buffer integration  no
  Shm emulation server buffer integration  no
  Vulkan-based server buffer integration . no
Qt Wayland Client Shell Integrations:
  xdg-shell .............................. no
  ivi-shell .............................. no
  wl-shell (deprecated) .................. yes
  qt-shell ............................... yes
Qt Wayland Compositor Layer Plugins:
  VSP2 hardware layer integration ........ no

ERROR: Qt Gui has been built without 'wayland' feature. This feature is required for building Qt Wayland Client.

CMake Error at /OE/build/luneos-styhead/tmp-glibc/work/corei7-64-webos-linux/qtwayland/6.7.2/recipe-sysroot/usr/lib/cmake/Qt6/QtBuildInformation.cmake:208 (message):
  Check the configuration messages for an error that has occurred.
Call Stack (most recent call first):
  /OE/build/luneos-styhead/tmp-glibc/work/corei7-64-webos-linux/qtwayland/6.7.2/recipe-sysroot/usr/lib/cmake/Qt6/QtBuildInformation.cmake:39 (qt_configure_print_summary)
  /OE/build/luneos-styhead/tmp-glibc/work/corei7-64-webos-linux/qtwayland/6.7.2/recipe-sysroot/usr/lib/cmake/Qt6/QtBuildRepoHelpers.cmake:347 (qt_print_feature_summary)
  /OE/build/luneos-styhead/tmp-glibc/work/corei7-64-webos-linux/qtwayland/6.7.2/recipe-sysroot/usr/lib/cmake/Qt6/QtBuildRepoHelpers.cmake:506 (qt_build_repo_end)
  CMakeLists.txt:42 (qt_build_repo)

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>