googletest-clang: rename to match googletest recipe name from meta-oe
require doesn't support any wildcards in filename so we need
to require the matching one and it was recently renamed from
_1.15.2.bb to _1.16.0.bb.

Fixes parsing error:

  ERROR: ParseError at meta-webos/recipes-test/googletest/googletest-clang_1.15.2.bb:5:
  Could not include required file recipes-test/googletest/googletest_1.15.2.bb
  ERROR: Parsing halted due to errors, see error messages above

after:
https://git.openembedded.org/meta-openembedded/commit/?id=375549bdbfa130a07ed4daddb7f8fa9a89da4964

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>