telegraf: Add recipe, required by com.webos.service.sdkagent
Loaded 4563 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'telegraf' (but /media/herrie/LuneOS/kirkstone/webos-ports/meta-webos-ports/meta-luneos/recipes-webos/com.webos.service.sdkagent/com.webos.service.sdkagent.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'telegraf' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['telegraf']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'com.webos.service.sdkagent', 'telegraf']

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>