connman-conf: fix build for qemu*
* qemuall append without leading space, which causes errors like this:
  ERROR: Fetcher failure: Unable to find file file://wired-setupfile://wired.config anywhere.