luna-service2: add systemd to REQUIRED_DISTRO_FEATURES
* has explicit dependency on systemd causing:
ERROR: Nothing PROVIDES 'systemd' (but /OE/build/oe-core/meta-webos-ports/meta-luneui/recipes-webos/luna-service2/luna-service2.bb DEPENDS on or otherwise requires it)
systemd was skipped: missing required distro features 'usrmerge systemd' (not in DISTRO_FEATURES)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'luna-service2', 'systemd']

* similarly recipes which explicitly depend on luna-service2:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'luna-service2' (but /OE/build/oe-core/meta-webos-ports/meta-luneui/recipes-webos/serviceinstaller/serviceinstaller.bb, /OE/build/oe-core/meta-webos-ports/meta-luneui/recipes-webos/luna-sysmgr-common/luna-sysmgr-co
mmon.bb, /OE/build/oe-core/meta-webos-ports/meta-luneui/recipes-webos/luna-prefs/luna-prefs.bb DEPENDS on or otherwise requires it)
luna-service2 was skipped: missing required distro feature 'systemd' (not in DISTRO_FEATURES)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'luna-next', 'luna-sysmgr-common', 'serviceinstaller', 'luna-service2']

Summary: There were 2 ERROR messages, returning a non-zero exit code.

NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'luna-sysmgr-common' (but /OE/build/oe-core/meta-webos-ports/meta-luneui/recipes-luneui/luna-next/luna-next.bb DEPENDS on or otherwise requires it)
luna-sysmgr-common was skipped: missing required distro feature 'systemd' (not in DISTRO_FEATURES)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'luna-next', 'luna-sysmgr-common']

Summary: There were 2 ERROR messages, returning a non-zero exit code.

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>