android-property-service: add dependency on virtual/android-headers
* needs android-config.h provided by android-headers-halium to fix:
  | In file included from /OE/build/luneos-master/webos-ports/tmp-glibc/work/tissot-webos-linux/android-property-service/0.1.0-2+gitAUTOINC+024e6ede51-r0/git/src/property_service.c:27:0:
  | /OE/build/luneos-master/webos-ports/tmp-glibc/work/tissot-webos-linux/android-property-service/0.1.0-2+gitAUTOINC+024e6ede51-r0/recipe-sysroot/usr/include/hybris/properties/properties.h:28:10: fatal error: android-config.h: No such file or directory
  |  #include <android-config.h>
  |           ^~~~~~~~~~~~~~~~~~
  | compilation terminated.
* and small fix in CMakeLists.txt, because since this commit:
  commit 35976c201741cfc21c114615b8524db5367e034a
  Author: Franz-Josef Haider <franz.haider@jolla.com>
  Date:   Thu May 17 11:42:35 2018 +0000

    hybris: properties: use system properties from bionic without hooks for android 8 and higher for simplicity

  /usr/include/hybris/properties/properties.h in libhybris includes
  android-config.h which is provided by android-headers-halium inside
  includedir/android:
  tmp-glibc/sstate-control/manifest-tissot-android-headers-halium.populate_sysroot:/OE/build/luneos-master/webos-ports/tmp-glibc/sysroots-components/tissot/android-headers-halium/usr/include/android/android-config.h
  tmp-glibc/sstate-control/manifest-hammerhead-android-headers-halium.populate_sysroot:/OE/build/luneos-master/webos-ports/tmp-glibc/sysroots-components/hammerhead/android-headers-halium/usr/include/android/android-config.h

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>