meta-luneos: add multimedia-layer to LAYERDEPENDS
* it was backported from newer meta-multimedia in kirkstone:
  https://github.com/webOS-ports/meta-webos-ports/commit/cbbcd6c71213fe6cc7e04c677c77ceb3f9d055a0
  but later split into backported recipe and a .bbappend:
  https://github.com/webOS-ports/meta-webos-ports/commit/d13a2a93da23c3d1a3525722f751d147aa82e194
  and in nanbield branch and newer the backported recipe was removed in:
  https://github.com/webOS-ports/meta-webos-ports/commit/4cdf2a73b7f2a9c2abf8f107c7bb81e5475711d9
  as meta-oe has newer version already.

* add dependency on meta-multimedia to fix:
  ERROR: No recipes in default available for:
    /OE/build/oe-core/meta-webos-ports/meta-luneos/recipes-multimedia/libcamera/libcamera_%.bbappend
  with nanbield and master

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>