maliit-framework-qt5: don't recommend any keyboard implementation
Causes compilation problems with the used keyboard implementation:

| compilation terminated.
| make[2]: *** [plugin.o] Error 1
| make[2]: *** Waiting for unfinished jobs....
| In file included from ../../../git/src/plugin/inputmethod.cpp:32:0:
| ../../../git/src/plugin/inputmethod.h:35:48: fatal error:
maliit/plugins/abstractinputmethod.h: No such file or directory
|  #include <maliit/plugins/abstractinputmethod.h>

Signed-off-by: Simon Busch <morphis@gravedo.de>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>