connman: move PACKAGECONFIG modification to .bbappend, remove dependency on xl2tp in signature
* we already have a bbappend, move the PACKAGECONFIG there
* skip xl2tp dependency from connman signature, because xl2tp is MACHINE_ARCH and connman is TUNE_PKGARCH
* fixes:
   === Comparing signatures for task do_package_write_ipk.sigdata between hammerhead and mako ===
  ERROR: connman different signature for task do_package_write_ipk.sigdata between hammerhead and mako
  NOTE: Starting bitbake server...
  Hash for dependent task xl2tpd/xl2tpd_git.bb.do_packagedata changed from 6312d5711b5c2c1a85ee235d09bf37a8ec00f7ad9e7248c087bb83ef1d5bd078 to c0d3ef52b37bda945d8b2a015980ddb8fe7b4b3dca3d82d71a84176cc5125142
  Unable to find matching sigdata for /OE/build/luneos-master/webos-ports/meta-openembedded/meta-networking/recipes-protocols/xl2tpd/xl2tpd_git.bb.do_packagedata with hashes 6312d5711b5c2c1a85ee235d09bf37a8ec00f7ad9e7248c087bb83ef1d5bd078 or c0d3ef52b37bda945d8b2a015980ddb8fe7b4b3dca3d82d71a84176cc5125142

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>