opkg: remove libsolv PACKAGECONFIG
* doesn't work for some reason
NOTE: recipe luneos-dev-image-1.0-r0: task do_rootfs: Started
ERROR: luneos-dev-image-1.0-r0 do_rootfs: Unable to install packages. Command '/OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/luneos-dev-image/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/luneos-dev-image/1.0-r0/opkg.conf -t /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/luneos-dev-image/1.0-r0/temp/ipktemp/ -o /OE/build/owpb/webos-ports/tmp-glibc/work/qemux86-webos-linux/luneos-dev-image/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install run-postinsts packagegroup-luneos-development packagegroup-webos-extended packagegroup-luneos-extended opkg packagegroup-core-ssh-openssh packagegroup-core-boot' returned 2:
Solver encountered 2 problem(s):
Problem 1/2:
  - package packagegroup-core-boot-1.0-r17.11.qemux86 requires systemd, but none of the providers can be installed

Solution 1:
  - do not ask to install a package providing packagegroup-core-boot

Problem 2/2:
  - package packagegroup-luneos-development-1.0-r0.11.qemux86 requires systemd-analyze, but none of the providers can be installed

Solution 1:
  - do not ask to install a package providing packagegroup-luneos-development

ERROR: luneos-dev-image-1.0-r0 do_rootfs: Function failed: do_rootfs

* both packages are correctly built and available in deploy/ipk/i586
* I've tried to remove our custom OPKGLIBDIR setting, but that didn't
  help as well, needs to be debugged a bit more

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>