com.webos.service.tts: Update 0001-google-add-gpr-lib-to-TTS_ENGINE-call.patch
Fixes:

/media/herrie/LuneOS/scarthgap/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/com.webos.service.tts/1.0.0-28/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/../../libexec/arm-webos-linux-gnueabi/gcc/arm-webos-linux-gnueabi/13.2.0/ld: CMakeFiles/tts-service.dir/media/herrie/LuneOS/scarthgap/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/com.webos.service.tts/1.0.0-28/recipe-sysroot/usr/include/google/api/metric.pb.cc.o: undefined reference to symbol '_ZN4absl12lts_2023080213hash_internal10CityHash32EPKcj'
/media/herrie/LuneOS/scarthgap/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/com.webos.service.tts/1.0.0-28/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/../../libexec/arm-webos-linux-gnueabi/gcc/arm-webos-linux-gnueabi/13.2.0/ld: /media/herrie/LuneOS/scarthgap/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/com.webos.service.tts/1.0.0-28/recipe-sysroot/usr/lib/libabsl_city.so.2308.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>