nyx-modules: disable security and security2 modules and return to the image
* security and security2 modules aren't compatible with openssl-1.1:
  /OE/build/luneos-thud/webos-ports/tmp-glibc/work/qemux86-webos-linux/nyx-modules/7.1.0-1+gitAUTOINC+af74a126de-r0/git/src/security/aes.c:145:17: error: storage size of 'ctx' isn't known
  /OE/build/luneos-thud/webos-ports/tmp-glibc/work/qemux86-webos-linux/nyx-modules/7.1.0-1+gitAUTOINC+af74a126de-r0/git/src/security2/aes.c:122:17: error: storage size of 'ctx' isn't known
  /OE/build/luneos-thud/webos-ports/tmp-glibc/work/qemux86-webos-linux/nyx-modules/7.1.0-1+gitAUTOINC+af74a126de-r0/git/src/security2/3des.c:71:17: error: storage size of 'ctx' isn't known
  /OE/build/luneos-thud/webos-ports/tmp-glibc/work/qemux86-webos-linux/nyx-modules/7.1.0-1+gitAUTOINC+af74a126de-r0/git/src/security2/hmac.c:43:11: error: storage size of 'hmacctx' isn't known
* that's why nyx-modules dependency was temporarily dropped from thud
  commit a595cc06dd26fd255307ce6fa0b7222a52dfd9f5
  Author: Martin Jansa <Martin.Jansa@gmail.com>
  Date:   Thu Sep 27 12:45:04 2018 +0000

    packagegroup: temoporary drop certmgrd, pmcertificatemgr, mojomail-imap, mojomail-pop, mojomail-smtp, nyx-modules

    * pmcertificatemgr and nyx-modules fail to build with openssl-1.1.1
    * mojomail-imap, mojomail-pop, mojomail-smtp depend on libpalmsocket which fails to build with openssl-1.1.1
* but completely missing nyx-modules are causing some extra issues like
  storaged, sleepd, nyx-utils systemd serices failing to start

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>