qtvideo-node, org.webosports.app.camera: fix PV
* SRCREV is the actual git sha, but for PV we need to use SRCPV which is sortable
  (thanks to PRserv)
* SRCPV is also shorter than SRCREV and fixes:
  OSError: [Errno 36] File name too long:
  '/home/jenkins/workspace/luneos-testing/webos-ports/sstate-cache/4f/sigtask.46ilehsh'
  ->
  '/home/jenkins/workspace/luneos-testing/webos-ports/sstate-cache/4f/sstate:org.webosports.app.camera:cortexa8t2hf-neon-halium-webos-linux-gnueabi:0.0.2-1+gita407b0443e7eb934c717723fbdedbd54ae631520:r0:cortexa8t2hf-neon-halium:3:4fe523e92b741f963d7538eaf9206ae8f0291d8593d6acfc89e563221f6c23bb_generate_toolchain_file.tgz.siginfo'

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>