python3-gbinder: upgrade to 1.1.2 as we have newer cython3 in scarthgap
* python3-cython upgraded in:
  https://git.openembedded.org/openembedded-core/commit/?id=21507a3be23a604259a6a903a7083db54d29487f

* 1.1.1 fails to build in scarthgap with:
ERROR: python3-gbinder-1.1.1+git-r0 do_compile: 'python3 setup.py bdist_wheel sdist --cython' execution failed.
ERROR: python3-gbinder-1.1.1+git-r0 do_compile: ExecutionError('/OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/python3-gbinder/1.1.1+git/temp/run.do_compile.11416', 1, None, None)
ERROR: Logfile of failure stored in: /OE/build/luneos-scarthgap/tmp-glibc/work/corei7-64-webos-linux/python3-gbinder/1.1.1+git/temp/log.do_compile.11416
Log data follows:
| DEBUG: Executing shell function do_compile
| performance hint: gbinder.pyx:68:5: Exception check on 'remote_object_local_notify_func' will always require the GIL to be acquired.
| Possible solutions:
| 	1. Declare 'remote_object_local_notify_func' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
| 	2. Use an 'int' return type on 'remote_object_local_notify_func' to allow an error code to be returned.
| performance hint: gbinder.pyx:205:5: Exception check on 'client_reply_func' will always require the GIL to be acquired.
| Possible solutions:
| 	1. Declare 'client_reply_func' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
| 	2. Use an 'int' return type on 'client_reply_func' to allow an error code to be returned.
| performance hint: gbinder.pyx:210:5: Exception check on 'local_destroy_notif' will always require the GIL to be acquired.
| Possible solutions:
| 	1. Declare 'local_destroy_notif' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
| 	2. Use an 'int' return type on 'local_destroy_notif' to allow an error code to be returned.
| performance hint: gbinder.pyx:672:5: Exception check on 'service_manager_get_service_func' will always require the GIL to be acquired.
| Possible solutions:
| 	1. Declare 'service_manager_get_service_func' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
| 	2. Use an 'int' return type on 'service_manager_get_service_func' to allow an error code to be returned.
| performance hint: gbinder.pyx:688:5: Exception check on 'service_manager_add_service_func' will always require the GIL to be acquired.
| Possible solutions:
| 	1. Declare 'service_manager_add_service_func' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
| 	2. Use an 'int' return type on 'service_manager_add_service_func' to allow an error code to be returned.
| performance hint: gbinder.pyx:691:5: Exception check on 'service_manager_func' will always require the GIL to be acquired.
| Possible solutions:
| 	1. Declare 'service_manager_func' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
| 	2. Use an 'int' return type on 'service_manager_func' to allow an error code to be returned.
| performance hint: gbinder.pyx:694:5: Exception check on 'service_manager_registration_func' will always require the GIL to be acquired.
| Possible solutions:
| 	1. Declare 'service_manager_registration_func' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
| 	2. Use an 'int' return type on 'service_manager_registration_func' to allow an error code to be returned.
|
| Error compiling Cython file:
| ------------------------------------------------------------
| ...
|             return True
|
|     def add_death_handler(self, notify_func):
|         if self._object is not NULL:
|             self.notify_func = notify_func
|             return cgbinder.gbinder_remote_object_add_death_handler(self._object, remote_object_local_notify_func, <void*>self)
|                                                                                   ^
| ------------------------------------------------------------
|
| gbinder.pyx:59:82: Cannot assign type 'void (GBinderRemoteObject *, void *) except * nogil' to 'GBinderRemoteObjectNotifyFunc'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (GBinderRemoteObject *, void *) except * nogil'.
...

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>