rdxd: move from meta-luneos to meta-luneui
* lune-service2 in meta-luneui depends on it
* found with yocto-check-layer:

INFO: ERROR: test_world (common.CommonCheckLayer)
INFO: ----------------------------------------------------------------------
INFO: Traceback (most recent call last):
  File "/OE/openembedded-core/scripts/lib/checklayer/cases/common.py", line 44, in test_world
    get_signatures(self.td['builddir'], failsafe=False)
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 281, in get_signatures
    check_command('Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.',
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 256, in check_command
    raise RuntimeError(msg)
RuntimeError: Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.
Command: BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BB_SIGNATURE_HANDLER" BB_SIGNATURE_HANDLER="OEBasicHash" bitbake -S none world
Output:
Loading cache...done.
Loaded 4109 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies
NOTE: Multiple providers are available for runtime ssh (dropbear, openssh)
Consider defining a PREFERRED_RPROVIDER entry to match ssh
ERROR: Nothing RPROVIDES 'rdxd' (but /OE/meta-webos-ports/meta-luneui/recipes-webos/luna-service2/luna-service2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'rdxd' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rdxd']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'luna-service2', 'rdxd']

Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>